import type { SingaporeSpecies } from './species-data';

const birdList = 'https://www.nparks.gov.sg/nature/species-list/birds';
const reptileList = 'https://www.nparks.gov.sg/nature/species-list/reptiles';
const frogList = 'https://www.nparks.gov.sg/nature/species-list/amphibians';
const gardens = 'https://juronglakegardens.nparks.gov.sg/birds/';
const herps = 'https://juronglakegardens.nparks.gov.sg/reptiles-and-amphibians/';
const guidance = 'https://www.nparks.gov.sg/visit/when-visiting-parks/when-encountering-animals';
type Entry = Pick<SingaporeSpecies, 'id'|'name'|'scientific'|'family'|'habitats'|'summary'|'identification'|'diet'|'behaviour'|'reproduction'|'ecologicalRole'|'pressures'> & {
  group?: SingaporeSpecies['group']; origin?: SingaporeSpecies['origin']; activity?: string;
  aliases?: string[]; sourceUrl?: string; extraSources?: string[]; statusCode?: 'LC'|'NA'|'UNV';
  taxonomyNote?: string; statusNote?: string; singapore?: string;
  facts: [string,string,string,string];
  factSources?: [string, string];
};
const entries: Entry[] = [
  {
    id:'yellow-vented-bulbul', name:'Yellow-vented bulbul', scientific:'Pycnonotus goiavier', family:'Pycnonotidae',
    habitats:['Parks','Gardens','Woodland','Mangroves'],
    summary:'A familiar garden songbird with a pale face and yellow feathers below the tail.',
    identification:'Brown back, dark crown and eye stripe, white eyebrow and throat, and a yellow vent. About 20 cm long.',
    diet:'Fruit, nectar and small invertebrates.',
    behaviour:'Often searches shrubs in pairs. It readily uses open greenery around homes.',
    reproduction:'Builds a cup nest from plant material, hidden among vegetation.',
    ecologicalRole:'Carries seeds between feeding sites and eats small invertebrates.',
    pressures:'Loss of shrubs and disturbance during nesting reduce usable garden habitat.',
    extraSources:[gardens],
    facts:['Look under the tail','The yellow vent is a useful clue when the bird turns away.','A garden neighbour','This very common resident uses gardens as well as wooded habitats.'],
  },
  {
    id:'asian-glossy-starling', name:'Asian glossy starling', scientific:'Aplonis panayensis', family:'Sturnidae',
    habitats:['Parks','Gardens','Forest','Mangroves','Urban'],
    summary:'A social fruit-eating bird whose green sheen can look black in shade.',
    identification:'Adults have red eyes, a dark bill and glossy green plumage. Young birds have streaked pale underparts.',
    diet:'Mostly fruit, with insects and nectar.',
    behaviour:'Feeds and roosts in noisy groups; communal roosts may contain many birds.',
    reproduction:'Uses cavities for nesting. A regional field observation records a pair carrying leaves into a palm cavity; juveniles have streaked plumage before acquiring the glossy adult appearance.',
    extraSources:['https://besgroup.org/2012/12/03/asian-glossy-starling-nesting-material-and-preening/'],
    ecologicalRole:'Disperses seeds from fruit and consumes insects.',
    pressures:'Tree removal can remove feeding and roosting sites. Disturbance affects nesting birds.',
    facts:['Green in the light','Adult feathers can look green in good light and almost black in shade.','A different childhood outfit','Juveniles have streaks instead of the adult glossy plumage.'],
  },
  {
    id:'common-tailorbird', name:'Common tailorbird', scientific:'Orthotomus sutorius', family:'Cisticolidae',
    habitats:['Gardens','Parks','Scrub','Forest edge'],
    summary:'A small, active bird that searches dense shrubs and makes a leaf-wrapped nest.',
    identification:'Olive-green upperparts, pale underside, a rusty forehead and a slim pale bill. Often holds its tail upright.',
    diet:'Small insects and other invertebrates gathered from vegetation.',
    behaviour:'Flits between bushes and often stays hidden despite being a common resident.',
    reproduction:'Uses plant fibres or spider silk to join leaf edges around the nest.',
    ecologicalRole:'Consumes small plant-dwelling invertebrates.',
    pressures:'Heavy hedge trimming can remove cover and damage occupied nests.',
    extraSources:[gardens],
    facts:['A leaf tailor','It joins leaf edges using fibres or spider silk.','Small and secretive','Dense shrubs can hide this very common resident from view.'],
    factSources:[gardens,'https://singaporebirds.com/species/common-tailorbird/'],
  },
  {
    id:'spotted-dove', name:'Spotted dove', scientific:'Spilopelia chinensis', family:'Columbidae', aliases:['Streptopelia chinensis'],
    habitats:['Grassland','Parks','Gardens','Urban'],
    summary:'A ground-feeding dove recognised by its white-spotted black neck patch.',
    identification:'Grey-brown body, grey face and pinkish breast. The spotted collar separates it from the smaller, barred zebra dove.',
    diet:'Seeds and grains collected on the ground.',
    behaviour:'Walks through open ground, usually alone, in pairs or in small groups.',
    reproduction:'Builds a sparse nest of fine twigs. Both parents incubate the eggs and care for the young; local breeding dates are not inferred from observations overseas.',
    extraSources:['https://birdlife.org.au/bird-profiles/spotted-dove/'],
    ecologicalRole:'Connects grass seeds and grain to the food web.',
    pressures:'Loss of open feeding areas and disturbance around nests can affect local birds.',
    facts:['Spots, not stripes','Its black collar has white spots; a zebra dove has fine bars.','A walking seed hunter','It normally gathers seeds while walking on the ground.'],
  },
  {
    id:'zebra-dove', name:'Zebra dove', scientific:'Geopelia striata', family:'Columbidae',
    habitats:['Grassland','Parks','Gardens','Urban'],
    summary:'A small, slender dove with fine dark bars and a soft cooing call.',
    identification:'Pale grey face, blue skin around the eyes, barred brown-grey back and barred sides. Smaller than the spotted dove.',
    diet:'Small seeds and occasional insects.',
    behaviour:'Forages in pairs or small groups on bare ground and short grass.',
    reproduction:'Makes a simple platform nest using leaves and grass.',
    ecologicalRole:'Feeds on small seeds and is prey for larger animals.',
    pressures:'Nest disturbance and loss of quiet ground-feeding spaces affect local habitat quality.',
    extraSources:[gardens],
    facts:['A striped dove','Fine bars on the neck and sides give this dove its name.','Ground-level dining','Short lawns and bare ground make seeds accessible to this small bird.'],
  },
  {
    id:'pink-necked-green-pigeon', name:'Pink-necked green pigeon', scientific:'Treron vernans', family:'Columbidae',
    habitats:['Forest','Parks','Gardens','Mangroves'],
    summary:'A green pigeon that feeds in trees, often disappearing among leaves.',
    identification:'Males have a pink neck and orange breast patch; females are mostly green. Both have a compact pigeon shape.',
    diet:'Fruit, including small fruits from trees.',
    behaviour:'Stays mainly in trees and gathers in flocks at fruiting branches.',
    reproduction:'Both parents share incubation and care of the chicks.',
    ecologicalRole:'Disperses seeds after feeding on fruit.',
    pressures:'Loss of fruiting trees reduces feeding opportunities.',
    extraSources:[gardens],
    facts:['Only he wears pink','The male has the pink neck; the female is mainly green.','A tree-loving pigeon','It seldom visits the ground except to drink.'],
  },
  {
    id:'brown-throated-sunbird', name:'Brown-throated sunbird', scientific:'Anthreptes malacensis', family:'Nectariniidae',
    habitats:['Parks','Gardens','Forest edge','Mangroves'],
    summary:'A sturdy sunbird found around flowering trees and shrubs.',
    identification:'The male has a brown throat, glossy green upperparts and yellow belly. Females are olive with a pale eye ring.',
    diet:'Nectar and small invertebrates, including spiders.',
    behaviour:'Visits both trees and low shrubs, using its bill to reach flowers.',
    reproduction:'Builds a hanging pouch nest from plant material and spider web.',
    ecologicalRole:'Transfers pollen while visiting flowers and eats small invertebrates.',
    pressures:'Removal of flowering plants and disturbance to hanging nests can reduce local habitat quality.',
    extraSources:[gardens],
    facts:['A sturdy flower visitor','Its robust shape and relatively straight bill help distinguish it from other sunbirds.','Two different outfits','The male is glossy and colourful; the female is mostly olive.'],
  },
  {
    id:'scarlet-backed-flowerpecker', name:'Scarlet-backed flowerpecker', scientific:'Dicaeum cruentatum', family:'Dicaeidae',
    habitats:['Gardens','Parks','Forest edge','Orchards'],
    summary:'A tiny bird that searches fruiting and flowering vegetation.',
    identification:'Males have a scarlet back, dark wings and pale belly. Females are brown above with a red rump. About 9 cm long.',
    diet:'Small fruit, flowers and insects; mistletoe fruit is an important food.',
    behaviour:'Moves through branches in search of flowers and fruit.',
    reproduction:'Builds a suspended pouch nest with a side opening.',
    ecologicalRole:'Moves seeds, including mistletoe seeds, between trees.',
    pressures:'Loss of fruiting vegetation reduces food and shelter.',
    extraSources:[gardens],
    facts:['Pocket-sized bird','At around 9 cm, it is much smaller than a garden bulbul.','Look for the rump','Females lack the male’s scarlet back but have a red rump.'],
  },
  {
    id:'common-iora', name:'Common iora', scientific:'Aegithina tiphia', family:'Aegithinidae',
    habitats:['Parks','Gardens','Woodland','Mangroves'],
    summary:'A yellow and green canopy bird with contrasting pale wing bars.',
    identification:'Yellow underparts and two white wing bars. Breeding males have more black on the head and back; females are greener.',
    diet:'Insects found among foliage.',
    behaviour:'Searches leaves in tree crowns, including their undersides.',
    reproduction:'Uses spider web in nest construction. Regional field observations record both parents incubating the eggs; these observations do not establish a Singapore breeding calendar.',
    ecologicalRole:'Consumes insects in the tree canopy.',
    pressures:'Loss of leafy trees removes feeding and nesting habitat.',
    extraSources:['https://besgroup.org/2014/07/23/nesting-of-the-common-iora-2-incubation/'],
    facts:['Check the wings','Two white wing bars help identify this yellow bird.','Under-leaf search','It searches the undersides of leaves for insects.'],
  },
  {
    id:'white-breasted-waterhen', name:'White-breasted waterhen', scientific:'Amaurornis phoenicurus', family:'Rallidae',
    habitats:['Wetlands','Ponds','Parks','Mangroves'],
    summary:'A long-legged rail often seen walking beside water and dense plants.',
    identification:'White face and breast, dark grey back, yellow legs and a greenish-yellow bill with red near the base.',
    diet:'Invertebrates, small aquatic animals and plant food.',
    behaviour:'Walks along wet edges and can swim. Often steps quickly into vegetation when disturbed.',
    reproduction:'An egg-laying wetland bird whose young chicks have black, fluffy down. Juveniles later become brown-grey before developing adult plumage.',
    ecologicalRole:'Feeds across the boundary between water and land.',
    pressures:'Clearing banks and wetland vegetation reduces shelter and nesting cover.',
    extraSources:['https://biodiversitysg.nparks.gov.sg/our-biodiversity/birds/other-birds/white-breasted-waterhen/'],
    facts:['A swimmer too','This walking wetland bird can also swim.','A white front','The white face and chest stand out against its dark upperparts.'],
  },
  {
    id:'white-throated-kingfisher', name:'White-throated kingfisher', scientific:'Halcyon smyrnensis', family:'Alcedinidae', aliases:['White-breasted kingfisher'],
    habitats:['Parks','Gardens','Canals','Mangroves','Grassland'],
    summary:'A bright blue-and-chestnut hunter that takes much more than fish.',
    identification:'Chestnut head and belly, white throat and breast, blue back and a large red bill.',
    diet:'Fish, insects, frogs, lizards and other small vertebrates.',
    behaviour:'Watches from a perch before dropping onto prey. Can hunt well away from open water.',
    reproduction:'Excavates a nesting tunnel in an earth bank; eggs are placed in the chamber at its end.',
    ecologicalRole:'A predator linking terrestrial and aquatic prey to the bird food web.',
    pressures:'Removal of hunting perches and disturbance or destruction of nesting banks reduce habitat.',
    extraSources:['https://animaldiversity.org/accounts/Halcyon_smyrnensis/'],
    facts:['More than fish','Its prey includes reptiles, insects and amphibians.','A perch is a lookout','It waits on a perch before striking at prey.'],
  },
  {
    id:'common-sun-skink', name:'Common sun skink', scientific:'Eutropis multifasciata', family:'Scincidae', group:'Reptile', aliases:['Many-lined sun skink','Eutropis multifasciatus','Mabuya multifasciata'],
    habitats:['Parks','Forest','Mangroves'], sourceUrl:'https://www.nparks.gov.sg/florafaunaweb/fauna/3/2/324',
    summary:'A sturdy, shiny-scaled lizard found around wooded ground and park paths.',
    identification:'Bronze-brown body, overlapping keeled scales and possible thin dark stripes. Some animals have orange along the sides.',
    diet:'Mainly insects.', activity:'Active by day; often basks in sunny patches.',
    behaviour:'Uses ground cover for shelter and moves between feeding and basking areas.',
    reproduction:'Gives birth to live young rather than laying a clutch of shelled eggs.',
    ecologicalRole:'Consumes insects and provides prey for larger animals.',
    pressures:'Loss of ground cover reduces shelter; avoid disturbing animals beside paths.',
    taxonomyNote:'NParks Flora & Fauna Web uses Eutropis multifasciata; the RDB3 list prints Eutropis multifasciatus. Both refer to the common sun skink here.',
    facts:['Live arrivals','This skink gives birth to live young.','A shining coat','Its overlapping scales give the body a shiny appearance.'],
  },
  {
    id:'field-frog', name:'Field frog', scientific:'Fejervarya limnocharis', family:'Dicroglossidae', group:'Amphibian', aliases:['Grass frog'],
    habitats:['Ponds','Gardens','Urban','Grassland'], sourceUrl:'https://www.nparks.gov.sg/publications-resources/articles/what-s-the-frog', extraSources:[herps],
    summary:'A small brown frog that breeds in shallow freshwater near open ground.',
    identification:'Brown or grey back with irregular dark blotches, strong hind legs and partly webbed hind feet.',
    diet:'Small invertebrates, including insects.', activity:'Mostly nocturnal; calls are more noticeable around breeding water.',
    behaviour:'Shelters near the ground and uses shallow puddles and ditches; tadpoles live near the bottom.',
    reproduction:'Lays large clutches of eggs in still water. Aquatic tadpoles develop into frogs.',
    ecologicalRole:'Links small invertebrates to wetland predators; its life cycle connects water and land.',
    pressures:'Drainage, polluted water and loss of small breeding pools can reduce habitat.',
    facts:['Powerful jumper','Its muscular hind legs provide the force for jumping.','Half-webbed feet','Its hind feet have partial webbing, unlike the more extensively webbed crab-eating frog.'],
    factSources:[herps,herps],
  },
  {
    id:'rock-pigeon', name:'Rock pigeon', scientific:'Columba livia', family:'Columbidae', origin:'Introduced', statusCode:'NA', aliases:['Rock dove','Feral pigeon'],
    habitats:['Urban','Parks','Buildings'], sourceUrl:'https://animaldiversity.org/accounts/Columba_livia/', extraSources:['https://singaporebirds.com/species/rock-dove/'],
    summary:'A familiar city pigeon descended from domesticated rock doves.',
    identification:'Often grey with two dark wing bars and an iridescent neck. Feral birds also have white, dark or reddish plumage.',
    diet:'Mostly seeds and grains; also takes discarded human food.',
    behaviour:'Feeds and roosts in groups, walking with a characteristic head-bobbing movement.',
    reproduction:'Both parents incubate the eggs and care for the young. Buildings provide nesting ledges.',
    ecologicalRole:'An urban seed eater and prey animal. Large feeding concentrations can create conflict with people.',
    pressures:'Human feeding concentrates flocks. Avoid feeding or encouraging dependence on food waste.',
    singapore:'NParks lists the rock dove as introduced in Singapore. City populations are feral birds, not a native pigeon population.',
    facts:['Many colours, one species','Feral rock pigeons can have very different plumage colours.','Buildings replace cliffs','Urban ledges provide shelter similar to the cliffs used by wild rock doves.'],
  },
  {
    id:'changeable-lizard', name:'Changeable lizard', scientific:'Calotes versicolor', family:'Agamidae', group:'Reptile', origin:'Introduced', statusCode:'UNV', aliases:['Oriental garden lizard'],
    habitats:['Urban','Parks','Gardens','Forest edge'], sourceUrl:'https://www.nparks.gov.sg/florafaunaweb/fauna/4/8/483', extraSources:[herps],
    summary:'An introduced garden lizard commonly seen on trunks, fences and sunny ground.',
    identification:'A long tail, rough scales and a crest of spines along the neck and back. Breeding males develop orange-red heads.',
    diet:'Insects and small lizards.', activity:'Active by day; basks to warm its body.',
    behaviour:'Climbs trunks and may move to the far side when approached.',
    reproduction:'Lays eggs on land. Males display stronger head colour during breeding.',
    ecologicalRole:'Consumes insects and small animals in urban food webs.',
    pressures:'Introduced species can compete with native wildlife; do not move or release lizards into new areas.',
    taxonomyNote:'Uses the name Calotes versicolor on the linked NParks account. Do not assign a revised species name from an unverified photograph.',
    statusNote:'NParks describes this introduced lizard as common. No matching national RDB3 category was verified; common is an encounter description, not a threat category.',
    facts:['Not a chameleon','This is an agamid lizard, not a chameleon.','Breeding colours','Males develop stronger orange-red head colours during breeding.'],
  },
  {
    id:'asian-toad', name:'Asian toad', scientific:'Duttaphrynus bengalensis', family:'Bufonidae', group:'Amphibian', origin:'Introduced', statusCode:'NA', aliases:['Common Asian toad','Asian common toad','Duttaphrynus melanostictus','Bufo melanostictus'],
    habitats:['Urban','Gardens','Grassland','Ponds'], sourceUrl:'https://biodiversitysg.nparks.gov.sg/our-biodiversity/amphibians/common-asian-toad/',
    summary:'A widespread urban toad that often hunts insects near lights after dark.',
    identification:'Bumpy skin, bony ridges behind the eyes and large glands behind the head. Colour varies from yellowish to dark brown.',
    diet:'Insects and other small invertebrates.', activity:'Mostly nocturnal; shelters under logs and leaf litter by day.',
    behaviour:'Forages on the ground, including near lights that attract insects.',
    reproduction:'Breeds in water; tadpoles develop in still or slow-moving freshwater before becoming land-dwelling toadlets.',
    ecologicalRole:'Consumes invertebrates and links freshwater breeding habitats to terrestrial food webs.',
    pressures:'Roads, drainage and contaminated water can affect toads. Do not release them into new habitats.',
    taxonomyNote:'The current NParks RDB3 list uses Duttaphrynus bengalensis. The May 2026 BiodiversitySG account uses Duttaphrynus melanostictus. These source labels are retained as searchable aliases, not separate profiles.',
    statusNote:'Current NParks sources classify the Singapore Asian toad as introduced; RDB3 assigns Not Applicable. Older pages that label it native are not used for origin.',
    facts:['A toad is a frog','True toads belong to the frog family Bufonidae.','Glands for defence','Glands behind the head can release defensive toxins; observe without touching.'],
  },
];

export const COMMON_SPECIES_EXPANSION: SingaporeSpecies[] = entries.map(entry => {
  const { facts, factSources, extraSources = [], ...fields } = entry;
  const group = entry.group ?? 'Bird';
  const statusCode = entry.statusCode ?? 'LC';
  const statusSourceUrl = group === 'Bird' ? birdList : group === 'Reptile' ? reptileList : frogList;
  const sourceUrl = entry.sourceUrl ?? `https://singaporebirds.com/species/${entry.id}/`;
  const status = statusCode === 'LC' ? 'Least Concern' : statusCode === 'NA' ? 'Not Applicable' : 'Not assessed here';
  return {
    ...fields, group, origin:entry.origin ?? 'Native', aliases:entry.aliases ?? [],
    pressures:`Habitat considerations: ${entry.pressures}`,
    emoji:group === 'Bird' ? '🐦' : group === 'Reptile' ? '🦎' : '🐸',
    encounter:'Commonly seen', habitat:entry.habitats.join(', '), rarity:'Common in suitable habitat; encounters are not guaranteed',
    activity:entry.activity ?? 'Often observed feeding by day.',
    singapore:entry.singapore ?? `Recorded in Singapore in ${entry.habitats.join(', ').toLowerCase()}. Observe from public paths; the guide does not identify nest locations.`,
    watch:'Watch quietly from a distance. Do not feed, catch, handle or approach nests. Leave animals an escape route.',
    statusCode, singaporeStatus:status, statusSourceUrl,
    statusNote:entry.statusNote ?? `Singapore RDB3: ${status}. National status is separate from global risk and local encounter frequency.`,
    globalStatus:'Dated global assessment not verified in this edition', globalSourceUrl:'', reviewedAt:'2026-09-14',
    sourceUrl, sourceName:sourceUrl.includes('singaporebirds.com') ? 'Bird Society of Singapore' : sourceUrl.includes('animaldiversity') ? 'Animal Diversity Web' : 'NParks',
    fact:facts[1], funFacts:[{title:facts[0],text:facts[1],sourceUrl:factSources?.[0] ?? sourceUrl},{title:facts[2],text:facts[3],sourceUrl:factSources?.[1] ?? sourceUrl}],
    sources:[{name:'Species account',url:sourceUrl,supports:'Identification, habitat and natural history'},
      ...extraSources.map(url => ({name:url.includes('nparks') ? 'NParks · supporting natural history' : url.includes('besgroup.org') ? 'Bird Ecology Study Group · regional field observation' : url.includes('animaldiversity.org') ? 'Animal Diversity Web' : url.includes('birdlife.org.au') ? 'BirdLife Australia · species biology' : 'Bird Society of Singapore',url,supports:'Additional ecology, identification and breeding information; overseas observations do not establish local dates'})),
      {name:'NParks · Singapore Red Data Book 3',url:statusSourceUrl,supports:'National conservation category and origin where listed'},
      {name:'NParks · responsible wildlife observation',url:guidance,supports:'Safe encounters and avoiding disturbance'}],
  };
});
