import type { SingaporeSpecies } from "./species-data";

const marineStatus = "https://www.nparks.gov.sg/nature/species-list/marine-mammals";
const terrestrialStatus = "https://www.nparks.gov.sg/nature/species-list/terrestrial-mammals";
const encounterGuidance = "https://www.nparks.gov.sg/visit/when-visiting-parks/when-encountering-animals";
const shared = {
  origin: "Native",
  reviewedAt: "2026-09-14",
  globalStatus: "Dated global assessment not verified in this edition",
  globalSourceUrl: "",
} as const;

export const NATIVE_SPECIES_EXPANSION: SingaporeSpecies[] = [
  {
    ...shared,
    id: "irrawaddy-dolphin", name: "Irrawaddy dolphin", scientific: "Orcaella brevirostris", emoji: "🐬", group: "Mammal", family: "Delphinidae", aliases: ["Irrawaddy river dolphin"],
    habitat: "Shallow coasts, estuaries and sheltered marine waters", habitats: ["Marine", "Coast", "Estuary"], encounter: "Rare or restricted", rarity: "Rarely recorded in Singapore waters; no local abundance estimate is implied",
    statusCode: "CR", singaporeStatus: "Critically Endangered", statusSourceUrl: marineStatus, sourceUrl: "https://animaldiversity.org/accounts/Orcaella_brevirostris/", sourceName: "Animal Diversity Web · University of Michigan",
    summary: "A round-headed coastal dolphin recorded in Singapore waters. Despite its common name, it also uses marine and estuarine habitats rather than living only in rivers.",
    identification: "A blunt, rounded forehead with no obvious beak, a small triangular dorsal fin and broad, rounded flippers. Colour is usually slate-grey, paler underneath.",
    diet: "Fish, cephalopods and crustaceans captured in shallow water.", activity: "Surfaces to breathe between dives; local daily activity patterns are not established in this guide.",
    behaviour: "Usually seen in small groups. It is adapted to shallow, sometimes turbid water and may surface with a rolling movement that shows little of the body.",
    reproduction: "Females give birth to a single calf and nurse it. Published species accounts describe slow reproduction; they do not establish a Singapore calving season.",
    singapore: "NParks lists the Irrawaddy dolphin among Singapore's native marine mammals. A national listing confirms occurrence and risk category, not a predictable viewing site or resident population size.",
    ecologicalRole: "A predator of fish and other aquatic prey in coastal and estuarine food webs.",
    pressures: "Entanglement in fishing gear, vessel traffic, underwater noise, pollution and degradation of shallow-water habitat threaten populations across its range.",
    watch: "Observe from shore where possible. Boats must not chase, encircle, feed or separate dolphins; report strandings to local wildlife authorities.",
    fact: "Its rounded forehead meets the mouth without a long dolphin-like beak.",
    funFacts: [
      { title: "A dolphin without a long beak", text: "The Irrawaddy dolphin has a rounded forehead and no prominent beak.", sourceUrl: "https://animaldiversity.org/accounts/Orcaella_brevirostris/" },
      { title: "Not only a river animal", text: "It also lives in shallow coastal and estuarine waters.", sourceUrl: "https://animaldiversity.org/accounts/Orcaella_brevirostris/" },
    ],
    statusNote: "Singapore RDB3 lists this native marine mammal as Critically Endangered. That national category is separate from any global assessment.",
    sources: [
      { name: "NParks · Marine mammals RDB3", url: marineStatus, supports: "Native occurrence and current Singapore conservation category" },
      { name: "Animal Diversity Web · University of Michigan", url: "https://animaldiversity.org/accounts/Orcaella_brevirostris/", supports: "Identification, habitat, diet, behaviour and reproduction" },
      { name: "NParks · wildlife encounter guidance", url: encounterGuidance, supports: "Responsible wildlife observation in Singapore" },
    ],
  },
  {
    ...shared,
    id: "false-killer-whale", name: "False killer whale", scientific: "Pseudorca crassidens", emoji: "🐬", group: "Mammal", family: "Delphinidae", aliases: ["False pilot whale"],
    habitat: "Deep offshore seas and oceanic waters", habitats: ["Marine", "Offshore"], encounter: "Rare or restricted", rarity: "Exceptional local record; the listing is not evidence of a resident population",
    statusCode: "UNV", singaporeStatus: "Not assessed here", statusSourceUrl: marineStatus, sourceUrl: "https://www.fisheries.noaa.gov/species/false-killer-whale", sourceName: "NOAA Fisheries",
    summary: "A large, dark oceanic dolphin whose name reflects a superficial resemblance to the killer whale. It is a member of the dolphin family.",
    identification: "A long, dark grey to black body, rounded forehead, no distinct beak and narrow flippers with a characteristic forward bend. The dorsal fin is tall and curved.",
    diet: "Large fish and cephalopods; some populations also take other marine mammals.", activity: "An active offshore swimmer that must surface to breathe; Singapore-specific activity data are not established.",
    behaviour: "Highly social and often travels in groups. Individuals may share prey, but behaviour varies among populations and encounters.",
    reproduction: "Females bear a single calf after a long pregnancy and provide extended care. No Singapore breeding season is inferred from general species accounts.",
    singapore: "NParks includes the false killer whale in the native marine-mammal list but records no Singapore RDB3 category for it. Rare occurrence should not be read as a population estimate.",
    ecologicalRole: "A high-level predator in offshore marine food webs.",
    pressures: "Fishing-gear interactions, prey depletion, contaminants, noise and mass-stranding events can affect the species.",
    watch: "Never approach or attempt to refloat a stranded cetacean without trained responders. At sea, keep a steady course and give animals space.",
    fact: "Despite its name, it is one of the larger members of the dolphin family.",
    funFacts: [
      { title: "A dolphin in disguise", text: "The false killer whale belongs to the oceanic dolphin family, Delphinidae.", sourceUrl: "https://www.fisheries.noaa.gov/species/false-killer-whale" },
      { title: "Built for open water", text: "Its long streamlined body and narrow flippers suit life in offshore seas.", sourceUrl: "https://www.fisheries.noaa.gov/species/false-killer-whale" },
    ],
    statusNote: "NParks lists the species as native but not evaluated (NE) in Singapore RDB3. AniQuest displays this as ‘Not assessed here’ rather than inventing a risk category.",
    sources: [
      { name: "NParks · Marine mammals RDB3", url: marineStatus, supports: "Native occurrence and absence of an assigned national category" },
      { name: "NOAA Fisheries", url: "https://www.fisheries.noaa.gov/species/false-killer-whale", supports: "Identification, ecology, reproduction and threats" },
      { name: "NParks · wildlife encounter guidance", url: encounterGuidance, supports: "Responsible wildlife observation in Singapore" },
    ],
  },
  {
    ...shared,
    id: "indo-pacific-bottlenose-dolphin", name: "Indo-Pacific bottlenose dolphin", scientific: "Tursiops aduncus", emoji: "🐬", group: "Mammal", family: "Delphinidae", aliases: ["Indian Ocean bottlenose dolphin"],
    habitat: "Shallow tropical coasts, bays and estuaries", habitats: ["Marine", "Coast", "Estuary"], encounter: "Rare or restricted", rarity: "Rarely recorded locally; sightings do not establish abundance",
    statusCode: "CR", singaporeStatus: "Critically Endangered", statusSourceUrl: marineStatus, sourceUrl: "https://animaldiversity.org/accounts/Tursiops_aduncus/", sourceName: "Animal Diversity Web · University of Michigan",
    summary: "A coastal bottlenose dolphin of the Indo-Pacific. It resembles the better-known common bottlenose dolphin, so reliable identification needs more than a quick glimpse.",
    identification: "A robust grey body, curved dorsal fin and a distinct medium-length beak. Adults may develop dark spotting on the underside; colour and spotting vary.",
    diet: "A range of coastal fish, squid and other cephalopods.", activity: "Travels, socialises and forages around the clock, with patterns shaped by prey and habitat.",
    behaviour: "Lives in flexible social groups whose membership can change. Individuals use whistles and echolocation while navigating and finding prey.",
    reproduction: "Usually one calf is born and remains dependent on its mother for an extended period. General timing must not be treated as a Singapore breeding forecast.",
    singapore: "NParks lists this dolphin as native and Critically Endangered nationally. Singapore waters are part of a busy coastal system, and records do not guarantee a sighting at any named shore.",
    ecologicalRole: "A mobile predator connecting fish communities across bays, estuaries and coastal waters.",
    pressures: "Vessel strikes, entanglement, underwater noise, pollution, prey change and coastal development can affect bottlenose dolphins.",
    watch: "Use binoculars from shore. On a vessel, do not cut across a group, follow closely, feed animals or separate a calf from adults.",
    fact: "Adults can develop dark spots on the paler underside.",
    funFacts: [
      { title: "Spots with age", text: "Some adults develop dark spotting on the underside as they mature.", sourceUrl: "https://animaldiversity.org/accounts/Tursiops_aduncus/" },
      { title: "A sound-built map", text: "Bottlenose dolphins use echolocation clicks to investigate their surroundings and prey.", sourceUrl: "https://animaldiversity.org/accounts/Tursiops_aduncus/" },
    ],
    statusNote: "Singapore RDB3 lists the native Indo-Pacific bottlenose dolphin as Critically Endangered.",
    sources: [
      { name: "NParks · Marine mammals RDB3", url: marineStatus, supports: "Native occurrence and current Singapore conservation category" },
      { name: "Animal Diversity Web · University of Michigan", url: "https://animaldiversity.org/accounts/Tursiops_aduncus/", supports: "Identification, diet, social behaviour and reproduction" },
      { name: "NParks · wildlife encounter guidance", url: encounterGuidance, supports: "Responsible wildlife observation in Singapore" },
    ],
  },
  {
    ...shared,
    id: "indo-pacific-finless-porpoise", name: "Indo-Pacific finless porpoise", scientific: "Neophocaena phocaenoides", emoji: "🌊", group: "Mammal", family: "Phocoenidae", aliases: ["Finless porpoise"],
    habitat: "Shallow coasts, estuaries and river mouths", habitats: ["Marine", "Coast", "Estuary"], encounter: "Rare or restricted", rarity: "Rarely seen in Singapore; surfacing animals can be difficult to detect",
    statusCode: "CR", singaporeStatus: "Critically Endangered", statusSourceUrl: marineStatus, sourceUrl: "https://animaldiversity.org/accounts/Neophocaena_phocaenoides/", sourceName: "Animal Diversity Web · University of Michigan",
    summary: "A small coastal cetacean with a smooth back instead of a dorsal fin. It favours shallow waters that are also heavily used by people.",
    identification: "A rounded forehead, no obvious beak and no dorsal fin. A low ridge with small bumps runs along the middle of the back; the body is grey.",
    diet: "Fish, shrimp, squid and other small aquatic prey.", activity: "Makes short, often inconspicuous surfacings to breathe and may be active by day or night.",
    behaviour: "Commonly travels alone or in small groups. It uses echolocation in shallow and sometimes turbid water.",
    reproduction: "Females usually bear one calf and nurse it. Species-level life history does not establish local birth dates or breeding sites.",
    singapore: "NParks lists this native porpoise as Critically Endangered in Singapore. Its low surfacing profile means absence of a sighting is not evidence of absence.",
    ecologicalRole: "A predator of small fish and invertebrates in shallow coastal food webs.",
    pressures: "Gill-net entanglement, vessel traffic, underwater noise, pollution and loss of productive coastal habitat are major concerns.",
    watch: "Never chase or crowd a porpoise. Slow down in an encounter, keep a steady course, and contact trained authorities for any stranded animal.",
    fact: "A low textured ridge replaces the dorsal fin found on most dolphins.",
    funFacts: [
      { title: "Finless really means finless", text: "This porpoise has no dorsal fin; a low ridge runs along its back instead.", sourceUrl: "https://animaldiversity.org/accounts/Neophocaena_phocaenoides/" },
      { title: "Quiet at the surface", text: "Its low, rolling surfacing can make it hard to notice even when the sea is calm.", sourceUrl: "https://animaldiversity.org/accounts/Neophocaena_phocaenoides/" },
    ],
    statusNote: "Singapore RDB3 lists the native Indo-Pacific finless porpoise as Critically Endangered.",
    sources: [
      { name: "NParks · Marine mammals RDB3", url: marineStatus, supports: "Native occurrence and current Singapore conservation category" },
      { name: "Animal Diversity Web · University of Michigan", url: "https://animaldiversity.org/accounts/Neophocaena_phocaenoides/", supports: "Identification, habitat, feeding, behaviour and reproduction" },
      { name: "NParks · wildlife encounter guidance", url: encounterGuidance, supports: "Responsible wildlife observation in Singapore" },
    ],
  },
  {
    ...shared,
    id: "sperm-whale", name: "Sperm whale", scientific: "Physeter macrocephalus", emoji: "🐋", group: "Mammal", family: "Physeteridae", aliases: ["Cachalot"],
    habitat: "Deep offshore seas and oceanic waters", habitats: ["Marine", "Offshore", "Deep water"], encounter: "Rare or restricted", rarity: "Exceptional local record; not a predictable Singapore sighting",
    statusCode: "UNV", singaporeStatus: "Not assessed here", statusSourceUrl: marineStatus, sourceUrl: "https://www.fisheries.noaa.gov/species/sperm-whale", sourceName: "NOAA Fisheries",
    summary: "The largest toothed whale, recognisable by its immense square head. A Singapore record documents occurrence, not a regular coastal population.",
    identification: "A very large dark body, block-shaped head, low rounded dorsal hump and a blowhole offset to the left. The narrow lower jaw carries the visible functional teeth.",
    diet: "Mainly squid, including deep-water species, as well as fish.", activity: "Alternates long deep foraging dives with recovery periods at the surface.",
    behaviour: "Females and young form social groups, while mature males may travel more widely. Echolocation clicks help whales navigate and hunt in darkness.",
    reproduction: "A female gives birth to one calf after a long pregnancy and nurses it for years. No local breeding claim is made from a rare Singapore occurrence.",
    singapore: "NParks includes the sperm whale on Singapore's native marine-mammal list without an assigned national risk category. An exceptional record must not be presented as a common resident.",
    ecologicalRole: "A deep-diving predator that transfers energy through oceanic food webs and transports nutrients between depth and surface.",
    pressures: "Entanglement, ship strikes, underwater noise, marine debris and contaminants can injure or displace sperm whales.",
    watch: "Keep far away at sea and never approach a stranded whale. Contact local wildlife and maritime authorities and follow the cordon set by responders.",
    fact: "It is the largest living toothed whale and specialises in deep dives.",
    funFacts: [
      { title: "A toothed giant", text: "The sperm whale is the largest of the toothed whales.", sourceUrl: "https://www.fisheries.noaa.gov/species/sperm-whale" },
      { title: "A left-sided blow", text: "Its blowhole sits toward the left front of its huge head, giving the blow a distinctive angle.", sourceUrl: "https://www.fisheries.noaa.gov/species/sperm-whale" },
    ],
    statusNote: "NParks lists the species as native but not evaluated (NE) in Singapore RDB3. AniQuest therefore shows no inferred national category.",
    sources: [
      { name: "NParks · Marine mammals RDB3", url: marineStatus, supports: "Native occurrence and absence of an assigned national category" },
      { name: "NOAA Fisheries", url: "https://www.fisheries.noaa.gov/species/sperm-whale", supports: "Identification, deep diving, social life, reproduction and threats" },
      { name: "NParks · wildlife encounter guidance", url: encounterGuidance, supports: "Responsible wildlife observation in Singapore" },
    ],
  },
  {
    ...shared,
    id: "common-treeshrew", name: "Common treeshrew", scientific: "Tupaia glis", emoji: "🐾", group: "Mammal", family: "Tupaiidae", aliases: ["Large treeshrew"],
    habitat: "Forest, secondary woodland, plantations and wooded parks", habitats: ["Forest", "Scrub", "Parks"], encounter: "Elusive", rarity: "Locally present in suitable woodland but easily overlooked",
    statusCode: "LC", singaporeStatus: "Least Concern", statusSourceUrl: terrestrialStatus, sourceUrl: "https://animaldiversity.org/accounts/Tupaia_glis/", sourceName: "Animal Diversity Web · University of Michigan",
    summary: "A quick, squirrel-like mammal of the forest floor and low branches. It is neither a true shrew nor a squirrel, despite the familiar comparisons.",
    identification: "A pointed snout, large eyes, rounded ears and a long bushy tail. A pale shoulder stripe helps distinguish it from similarly sized squirrels.",
    diet: "Insects and other small animals, together with fruit and other plant food.", activity: "Diurnal, with much foraging carried out on the ground and low vegetation.",
    behaviour: "Moves rapidly along logs, leaf litter and branches. Individuals use scent marking and defended home areas.",
    reproduction: "The species has small litters in a nest. Mothers use an unusual brief nursing pattern between visits; this is general biology, not a Singapore breeding calendar.",
    singapore: "NParks lists the common treeshrew as native and Least Concern nationally. It depends on vegetated habitat even when a record comes from near a park edge.",
    ecologicalRole: "An omnivore that eats small invertebrates and fruit, linking several parts of the forest food web and potentially moving seeds.",
    pressures: "Loss and fragmentation of wooded habitat, road traffic and disturbance can reduce safe movement and feeding areas.",
    watch: "Observe quietly from a trail. Do not bait it with food or chase it into cover for a photograph.",
    fact: "The pale stripe near its shoulder is a useful clue that it is not a squirrel.",
    funFacts: [
      { title: "Neither shrew nor squirrel", text: "Treeshrews form their own mammal order, Scandentia.", sourceUrl: "https://animaldiversity.org/accounts/Tupaia_glis/" },
      { title: "A shoulder-stripe clue", text: "A pale stripe near the shoulder helps identify the common treeshrew.", sourceUrl: "https://animaldiversity.org/accounts/Tupaia_glis/" },
    ],
    statusNote: "Singapore RDB3 lists the native common treeshrew as Least Concern.",
    sources: [
      { name: "NParks · Terrestrial mammals RDB3", url: terrestrialStatus, supports: "Native occurrence and current Singapore conservation category" },
      { name: "Animal Diversity Web · University of Michigan", url: "https://animaldiversity.org/accounts/Tupaia_glis/", supports: "Identification, diet, behaviour and reproduction" },
      { name: "NParks · wildlife encounter guidance", url: encounterGuidance, supports: "Responsible wildlife observation in Singapore" },
    ],
  },
  {
    ...shared,
    id: "cave-nectar-bat", name: "Cave nectar bat", scientific: "Eonycteris spelaea", emoji: "🦇", group: "Mammal", family: "Pteropodidae", aliases: ["Dawn bat", "Common dawn bat"],
    habitat: "Caves, forest edges, orchards, gardens and flowering trees", habitats: ["Cave", "Forest", "Parks", "Urban"], encounter: "Elusive", rarity: "Uncommon and mainly detected at night or at roosts",
    statusCode: "VU", singaporeStatus: "Vulnerable", statusSourceUrl: terrestrialStatus, sourceUrl: "https://animaldiversity.org/accounts/Eonycteris_spelaea/", sourceName: "Animal Diversity Web · University of Michigan",
    summary: "A long-snouted fruit bat specialised for feeding at flowers. By carrying pollen between plants, it provides an important nocturnal pollination service.",
    identification: "A medium-sized brown fruit bat with a long narrow muzzle, large eyes and a short tail. Its tongue and muzzle suit feeding from deep flowers.",
    diet: "Nectar and pollen, with soft fruit also eaten.", activity: "Nocturnal; leaves the day roost after dusk to visit flowering plants.",
    behaviour: "Roosts communally in caves or cave-like shelter and can travel several kilometres while feeding. It does not use laryngeal echolocation like many insect-eating bats.",
    reproduction: "Females normally bear a single young and nurse it. Regional reproductive timing must not be treated as a fixed Singapore calendar.",
    singapore: "NParks lists the cave nectar bat as native and Vulnerable. Feeding records around flowering trees do not identify or disclose a sensitive roost.",
    ecologicalRole: "A night-time pollinator of forest and cultivated plants, moving pollen between widely separated flowers.",
    pressures: "Disturbance or loss of communal roosts, removal of flowering trees and persecution can harm colonies and their pollination role.",
    watch: "Never enter or light a bat roost. Watch feeding bats from a distance, keep cats indoors at night and do not handle a grounded bat.",
    fact: "Pollen carried on its fur helps fertilise flowers visited after dark.",
    funFacts: [
      { title: "A night-shift pollinator", text: "Cave nectar bats carry pollen between flowers while feeding after dark.", sourceUrl: "https://www.merlintuttle.org/documenting-billion-dollar-bats/" },
      { title: "A flower-shaped toolkit", text: "Its elongated muzzle and tongue help it reach nectar inside deep flowers.", sourceUrl: "https://animaldiversity.org/accounts/Eonycteris_spelaea/" },
    ],
    statusNote: "Singapore RDB3 lists the native cave nectar bat as Vulnerable.",
    sources: [
      { name: "NParks · Terrestrial mammals RDB3", url: terrestrialStatus, supports: "Native occurrence and current Singapore conservation category" },
      { name: "Animal Diversity Web · University of Michigan", url: "https://animaldiversity.org/accounts/Eonycteris_spelaea/", supports: "Identification, feeding, roosting and reproduction" },
      { name: "Merlin Tuttle's Bat Conservation", url: "https://www.merlintuttle.org/documenting-billion-dollar-bats/", supports: "Pollination ecology and responsible bat conservation" },
    ],
  },
  {
    ...shared,
    id: "lesser-long-tongued-nectar-bat", name: "Lesser long-tongued nectar bat", scientific: "Macroglossus minimus", emoji: "🦇", group: "Mammal", family: "Pteropodidae", aliases: ["Long-tongued nectar bat", "Northern blossom bat"],
    habitat: "Mangroves, coastal woodland, gardens and flowering vegetation", habitats: ["Mangrove", "Coast", "Forest", "Parks"], encounter: "Elusive", rarity: "Uncommon and difficult to identify during brief night-time visits",
    statusCode: "VU", singaporeStatus: "Vulnerable", statusSourceUrl: terrestrialStatus, sourceUrl: "https://animaldiversity.org/accounts/Macroglossus_minimus/", sourceName: "Animal Diversity Web · University of Michigan",
    summary: "A small fruit bat with a long tongue adapted for sipping nectar. It uses coastal and wooded habitats where suitable flowers and roosts remain.",
    identification: "A small brown fruit bat with a narrow elongated muzzle, large eyes, small ears and a very long brush-tipped tongue. Close identification should be left to specialists.",
    diet: "Nectar and pollen, with soft fruit also taken.", activity: "Nocturnal, visiting flowers after dusk and resting by day in foliage or sheltered vegetation.",
    behaviour: "Often feeds alone at flowers and may hover briefly or cling while licking nectar. It carries pollen on its muzzle and fur.",
    reproduction: "Females bear live young and nurse them. Published regional timing does not establish a Singapore season or roost location.",
    singapore: "NParks lists the species as native and Vulnerable. Its use of mangroves and flowering vegetation makes coastal habitat quality important.",
    ecologicalRole: "A nocturnal pollinator that links flowering plants across coastal and wooded habitats.",
    pressures: "Mangrove loss, removal of night-flowering plants, roost disturbance and pesticide exposure can reduce food and shelter.",
    watch: "Watch from a respectful distance without flash. Never disturb a day roost or pick up a bat with bare hands.",
    fact: "A brush-tipped tongue helps collect nectar and pollen from flowers.",
    funFacts: [
      { title: "A tongue made for flowers", text: "Its long brush-tipped tongue is specialised for collecting nectar and pollen.", sourceUrl: "https://animaldiversity.org/accounts/Macroglossus_minimus/" },
      { title: "Pollination after sunset", text: "Pollen sticks to the bat as it moves between night-blooming flowers.", sourceUrl: "https://animaldiversity.org/accounts/Macroglossus_minimus/" },
    ],
    statusNote: "Singapore RDB3 lists the native lesser long-tongued nectar bat as Vulnerable.",
    sources: [
      { name: "NParks · Terrestrial mammals RDB3", url: terrestrialStatus, supports: "Native occurrence and current Singapore conservation category" },
      { name: "Animal Diversity Web · University of Michigan", url: "https://animaldiversity.org/accounts/Macroglossus_minimus/", supports: "Identification, diet, activity, behaviour and reproduction" },
      { name: "NParks · wildlife encounter guidance", url: encounterGuidance, supports: "Responsible wildlife observation in Singapore" },
    ],
  },
  {
    ...shared,
    id: "large-flying-fox", name: "Large flying fox", scientific: "Pteropus vampyrus", emoji: "🦇", group: "Mammal", family: "Pteropodidae", aliases: ["Large fruit bat", "Malayan flying fox"],
    habitat: "Mangroves, coastal forest and tall communal roost trees", habitats: ["Mangrove", "Coast", "Forest"], encounter: "Rare or restricted", rarity: "Rare and irregular in Singapore; roost locations are sensitive",
    statusCode: "CR", singaporeStatus: "Critically Endangered", statusSourceUrl: terrestrialStatus, sourceUrl: "https://animaldiversity.org/accounts/Pteropus_vampyrus/", sourceName: "Animal Diversity Web · University of Michigan",
    summary: "One of the world's largest bats, with a fox-like face and broad wings. It feeds on fruit and flowers and can move pollen and seeds over long distances.",
    identification: "A very large dark-winged fruit bat with a long fox-like muzzle, large eyes and contrasting mantle around the shoulders. It has no tail.",
    diet: "Fruit, nectar, pollen and flowers.", activity: "Nocturnal; leaves communal day roosts at dusk to forage across a wide area.",
    behaviour: "Roosts in groups high in trees and can travel long distances between roosts and feeding sites. It relies strongly on sight and smell.",
    reproduction: "Females generally bear one young and carry it when small. Life-history summaries do not establish local breeding dates or reveal roost sites.",
    singapore: "NParks lists the large flying fox as native and Critically Endangered nationally. Records may involve mobile animals, and exact roost locations should not be publicised.",
    ecologicalRole: "A long-distance pollinator and seed disperser that connects forest patches and coastal vegetation.",
    pressures: "Roost loss and disturbance, hunting elsewhere in its range, loss of feeding trees and conflict around fruit crops threaten populations.",
    watch: "Remain outside roost trees, keep noise and lights low and never fly drones near a colony. Do not handle grounded bats.",
    fact: "Its broad wings carry pollen and seeds between places separated by many kilometres.",
    funFacts: [
      { title: "A very large bat", text: "The large flying fox is among the biggest bats in the world.", sourceUrl: "https://animaldiversity.org/accounts/Pteropus_vampyrus/" },
      { title: "A forest connector", text: "By carrying pollen and seeds, flying foxes can connect plants across distant forest patches.", sourceUrl: "https://animaldiversity.org/accounts/Pteropus_vampyrus/" },
    ],
    statusNote: "Singapore RDB3 lists the native large flying fox as Critically Endangered.",
    sources: [
      { name: "NParks · Terrestrial mammals RDB3", url: terrestrialStatus, supports: "Native occurrence and current Singapore conservation category" },
      { name: "Animal Diversity Web · University of Michigan", url: "https://animaldiversity.org/accounts/Pteropus_vampyrus/", supports: "Identification, movement, diet, roosting and reproduction" },
      { name: "NParks · wildlife encounter guidance", url: encounterGuidance, supports: "Responsible wildlife observation in Singapore" },
    ],
  },
  {
    ...shared,
    id: "asian-small-clawed-otter", name: "Asian small-clawed otter", scientific: "Aonyx cinereus", emoji: "🦦", group: "Mammal", family: "Mustelidae", aliases: ["Oriental small-clawed otter", "Asian short-clawed otter"],
    habitat: "Mangroves, freshwater wetlands, streams and muddy banks", habitats: ["Mangrove", "Freshwater", "River", "Coast"], encounter: "Rare or restricted", rarity: "Rare in Singapore and much less often seen than the smooth-coated otter",
    statusCode: "CR", singaporeStatus: "Critically Endangered", statusSourceUrl: terrestrialStatus, sourceUrl: "https://animaldiversity.org/accounts/Aonyx_cinerea/", sourceName: "Animal Diversity Web · University of Michigan",
    summary: "The world's smallest otter species, with dexterous front paws used to feel for small prey. It must not be confused with Singapore's larger, more familiar smooth-coated otter.",
    identification: "A small dark-brown otter with a pale throat, short claws that do not extend beyond the fingertips and partly webbed paws. Size alone is not enough for a confident identification.",
    diet: "Crabs, molluscs and other aquatic invertebrates, along with frogs and small fish.", activity: "Can forage by day or night depending on disturbance, prey and local conditions.",
    behaviour: "Social and vocal, often foraging with sensitive paws in mud and shallow water. Family groups use dens and scent-marked areas.",
    reproduction: "A pair may raise a small litter with help from older group members. General species biology does not identify a Singapore den or breeding date.",
    singapore: "NParks lists the native Asian small-clawed otter as Critically Endangered. Any suspected record should be documented from a distance and checked by specialists.",
    ecologicalRole: "A predator of crabs, molluscs and other small wetland animals, linking shallow water and bank habitats.",
    pressures: "Wetland loss, water pollution, road traffic, disturbance and illegal wildlife trade affect small-clawed otters across their range.",
    watch: "Keep a wide distance, dogs leashed and the route to water clear. Never feed otters or share the location of a den.",
    fact: "Its sensitive, partly webbed paws help it feel for prey in mud and shallow water.",
    funFacts: [
      { title: "The smallest otter", text: "The Asian small-clawed otter is the smallest living otter species.", sourceUrl: "https://animaldiversity.org/accounts/Aonyx_cinerea/" },
      { title: "Paws before teeth", text: "It often uses sensitive front paws to search mud and crevices for small prey.", sourceUrl: "https://animaldiversity.org/accounts/Aonyx_cinerea/" },
    ],
    taxonomyNote: "Many references use Aonyx cinereus; the supporting Animal Diversity Web account retains the older combination Aonyx cinerea.",
    statusNote: "Singapore RDB3 lists the native Asian small-clawed otter as Critically Endangered.",
    sources: [
      { name: "NParks · Terrestrial mammals RDB3", url: terrestrialStatus, supports: "Native occurrence and current Singapore conservation category" },
      { name: "Animal Diversity Web · University of Michigan", url: "https://animaldiversity.org/accounts/Aonyx_cinerea/", supports: "Identification, foraging, social behaviour and reproduction" },
      { name: "NParks · wildlife encounter guidance", url: encounterGuidance, supports: "Responsible wildlife observation in Singapore" },
    ],
  },
];
