export type NewsStory = {
  feedId: string;
  emoji: string;
  topic: string;
  source: string;
  date: string;
  official: boolean;
  title: string;
  summary: string;
  lesson: string;
  href: string;
};

export const LOCAL_NEWS_FEEDS = [
  { id: "mothership", name: "Mothership", scope: "singapore" as const, url: "https://mothership.sg/category/environment/", official: false },
  { id: "mustsharenews", name: "MustShareNews", scope: "singapore" as const, url: "https://mustsharenews.com/category/singapore/environment/", official: false },
];

export const SINGAPORE_NEWS_STORIES: NewsStory[] = [
  { feedId: "nparks", emoji: "🦇", topic: "Wildlife health", source: "NParks", date: "5 Aug 2026", official: true, title: "Six projects receive Singapore biosurveillance grants", summary: "Research teams will study zoonotic risks involving domestic animals, urban birds, ticks and local mammals such as macaques and bats.", lesson: "Ask which animals, places and evidence each project will sample.", href: "https://www.nparks.gov.sg/news/news-detail/nparks-awards-grants-to-six-projects-under-biosurveillance-research-programme" },
  { feedId: "mothership", emoji: "🐍", topic: "Wildlife encounters", source: "Mothership", date: "27 Aug 2026", official: false, title: "Wild painted bronzeback released after Singapore Zoo encounter", summary: "Mandai staff moved a native, non-venomous snake from a crowded indoor area where it was at risk of injury, then released it into the wild.", lesson: "Give a snake space to retreat. Trained staff should intervene only when it is trapped or in distress.", href: "https://mothership.sg/2026/08/wild-snake-singapore-zoo-staff-caught/" },
  { feedId: "straits-times", emoji: "🐆", topic: "Wildlife technology", source: "The Straits Times", date: "22 Jun 2026", official: false, title: "Camera traps document Singapore wildlife", summary: "A Changi survey recorded five leopard cats using 18 motion-triggered cameras.", lesson: "A sighting is not a census.", href: "https://www.straitstimes.com/singapore/environment/eye-spy-what-camera-traps-have-uncovered-about-wildlife-in-singapore" },
  { feedId: "nparks", emoji: "🐸", topic: "Biodiversity", source: "NParks", date: "20 Jun 2026", official: true, title: "Pulau Ubin surveys add species and records", summary: "NParks reported more than 1,300 native fauna species, two discoveries new to science and a breeding Cryptic Painted Frog population.", lesson: "Separate a species new to science from a species newly recorded in Singapore.", href: "https://www.nparks.gov.sg/news/news-detail/new-e-publication-on-biodiversity-in-pulau-ubin-details-two-discoveries-new-to-science-and-27-new-records-for-singapore" },
  { feedId: "cna", emoji: "🦎", topic: "Wildlife rescue", source: "CNA", date: "20 May 2026", official: false, title: "ACRES announces plans to double sanctuary space", summary: "CNA reported in May that ACRES planned to double its sanctuary footprint by July. The sanctuary cares for rescued and confiscated animals.", lesson: "Rescue, rehabilitation and release are different stages with different evidence needs.", href: "https://www.channelnewsasia.com/singapore/wildlife-rescue-charity-acres-animals-rehabilitation-6129866" },
  { feedId: "nparks", emoji: "🦔", topic: "Wildlife trade", source: "NParks / ICA", date: "28 Mar 2026", official: true, title: "More than 830 kg of pangolin scales seized in transit", summary: "The March announcement described a 29 December 2025 seizure, estimated to represent more than 2,200 pangolins. It was Singapore's largest recorded Asian pangolin-scale seizure.", lesson: "Trade estimates are not wild population counts; check how an estimate was calculated.", href: "https://www.nparks.gov.sg/news/news-detail/national-parks-board-and-immigration---checkpoints-authority-foil-attempt-to-smuggle-over-830kg-of-asian-pangolin-scales" },
  { feedId: "cna", emoji: "🦜", topic: "Border protection", source: "CNA", date: "13 Feb 2026", official: false, title: "Singapore detected 28 animal-smuggling cases in 2025", summary: "The cases involved pets and protected wildlife; the reported total was lower than the 42 cases detected in 2024.", lesson: "A fall in detected cases does not by itself prove that all smuggling fell.", href: "https://www.channelnewsasia.com/singapore/animal-pet-smuggling-2025-drop-cases-illegal-wildlife-trade-5928981" },
  { feedId: "mustsharenews", emoji: "🐢", topic: "Wildlife observation", source: "MustShareNews", date: "13 Aug 2026", official: false, title: "Student finds an elusive spiny hill terrapin after a three-year search", summary: "A wildlife observer and his father noticed the well-camouflaged terrapin beside a boardwalk in the Central Catchment Nature Reserve.", lesson: "One sighting documents an encounter, not abundance. Stay on the boardwalk and protect sensitive locations.", href: "https://mustsharenews.com/student-spiny-terrapin-years/" },
];

export const WORLD_NEWS_STORIES: NewsStory[] = [
  { feedId: "associated-press", emoji: "🐧", topic: "Wildlife care", source: "Associated Press", date: "3 Sep 2026", official: false, title: "Injured Humboldt penguins test protective copper vests", summary: "Chilean carers are testing snug copper-and-zinc-threaded vests that protect wounds and may support healing.", lesson: "Ask how a treatment is tested before deciding that it works.", href: "https://apnews.com/article/6e93b8d4eaef903e4c85d16ade7d5881" },
  { feedId: "guardian", emoji: "🦜", topic: "Conservation", source: "The Guardian", date: "1 Sep 2026", official: false, title: "Record kākāpō breeding season", summary: "New Zealand’s managed kākāpō population reached 325 after 90 chicks were added.", lesson: "Compare counts across dated assessments.", href: "https://www.theguardian.com/world/2026/sep/01/record-breeding-worlds-heaviest-parrot-nz-endangered-kakapo" },
  { feedId: "science-news", emoji: "🪱", topic: "Animal movement", source: "Science News", date: "31 Aug 2026", official: false, title: "Blackworms move faster in tighter channels", summary: "Experiments found that California blackworms crossed tight, water-filled channels faster because walls constrained their motion.", lesson: "Compare the physical experiment with the computer model used to explain it.", href: "https://www.sciencenews.org/article/blackworms-move-faster-tight-tunnels" },
  { feedId: "mongabay", emoji: "🐋", topic: "Wildlife technology", source: "Mongabay", date: "31 Aug 2026", official: false, title: "Satellites can help find remote whale strandings", summary: "Very high-resolution images can extend records of strandings along remote coasts.", lesson: "Satellite evidence adds reach, but field checks and necropsies still matter.", href: "https://news.mongabay.com/2026/08/scientists-use-satellites-to-track-whale-strandings-in-remote-places-from-space/" },
  { feedId: "reuters", emoji: "🐻", topic: "Coexistence", source: "Reuters", date: "29 Aug 2026", official: false, title: "Food shortages drive more bear encounters in the US West", summary: "Poor natural food supplies and easy access to human food are increasing encounters in parts of the western United States.", lesson: "Separate the immediate trigger from longer-term habitat and climate pressures.", href: "https://www.reuters.com/world/us/hungry-bears-wander-into-us-west-homes-shops-record-numbers-2026-08-29/" },
  { feedId: "noaa", emoji: "🐟", topic: "Ocean change", source: "NOAA Fisheries", date: "24 Aug 2026", official: true, title: "Cooperative research tracks Atlantic mackerel movement", summary: "Scientists and fishing crews are combining surveys to study how ocean conditions affect where Atlantic mackerel are found.", lesson: "Use several kinds of evidence before explaining a population shift.", href: "https://www.fisheries.noaa.gov/feature-story/mackerel-move-cooperative-research-investigates-atlantic-mackerel-abundance-under" },
];

export const ALL_NEWS_STORIES = [...SINGAPORE_NEWS_STORIES, ...WORLD_NEWS_STORIES];
