import fullBirdProfiles from "./full-bird-profiles.json";
import commonBirdPhotos from "./common-bird-photos.json";
import additionalCommonPhotos from "./additional-common-photos.json";
import migratoryBirdPhotos from "./migratory-bird-photos.json";

/** Real reference photographs. Source and licence data are retained when published. */
export type WildlifePhotoRecord = { src: string; width: number; height: number; alt: string; name: string; location: string; date?: string; photographer: string; license?: string; licenseUrl?: string; sourceUrl: string; position: string };

export const PROFILE_PHOTOS: Record<string, WildlifePhotoRecord> = {
  ...commonBirdPhotos,
  ...additionalCommonPhotos,
  ...migratoryBirdPhotos,
  "oriental-whip-snake": {
    src:"https://juronglakegardens.nparks.gov.sg/images/Fauna/Ahaetulla_20prasina_Bigeye_20green_20whip_20snake_Daniel_20Ng.jpg",
    width:800,height:520,name:"Oriental whip snake",alt:"Oriental whip snake in green foliage, NParks reference photograph",
    photographer:"Daniel Ng / NParks",location:"NParks Jurong Lake Gardens reference photograph",
    sourceUrl:"https://juronglakegardens.nparks.gov.sg/reptiles-and-amphibians/",position:"50% 50%"
  },
  "green-paddy-frog": {
    src:"https://juronglakegardens.nparks.gov.sg/images/Fauna/Hylarana_20erythraea_Common_20Greenback_Daniel_20Ng.jpg",
    width:3872,height:2592,name:"Green paddy frog",alt:"Green paddy frog beside freshwater vegetation, NParks reference photograph",
    photographer:"Daniel Ng / NParks",location:"NParks Jurong Lake Gardens reference photograph",
    sourceUrl:"https://juronglakegardens.nparks.gov.sg/reptiles-and-amphibians/",position:"50% 50%"
  },
  "red-eared-slider": {
    src:"https://juronglakegardens.nparks.gov.sg/images/Fauna/Red_eared_slider_Cai_YX.jpg",
    width:500,height:335,name:"Red-eared slider",alt:"Red-eared slider freshwater turtle, NParks reference photograph",
    photographer:"Cai Yixiong / NParks",location:"NParks Jurong Lake Gardens reference photograph",
    sourceUrl:"https://juronglakegardens.nparks.gov.sg/reptiles-and-amphibians/",position:"50% 50%"
  },
  "common-sun-skink": {
    src: "https://www.nparks.gov.sg/-/media/ffw/migrated/round2/fauna/324/6414a53dab7c48cebd7291d2b75f4aa1.jpg",
    width: 500, height: 375, name: "Common sun skink",
    alt: "Common sun skink, NParks reference photograph", photographer: "Cheryl Chia",
    location: "NParks reference photograph", date: "18 Oct 2009",
    sourceUrl: "https://www.nparks.gov.sg/florafaunaweb/fauna/3/2/324", position: "50% 50%"
  },
  "field-frog": {
    src: "https://juronglakegardens.nparks.gov.sg/images/Fauna/Fejervarya_20limnocharis_Field_20Frog_Daniel_20Ng.jpg",
    width: 3872, height: 2592, name: "Field frog",
    alt: "Field frog, NParks Jurong Lake Gardens reference photograph", photographer: "Daniel Ng / NParks",
    location: "NParks Jurong Lake Gardens reference photograph",
    sourceUrl: "https://juronglakegardens.nparks.gov.sg/reptiles-and-amphibians/", position: "50% 50%"
  },
  "changeable-lizard": {
    src: "https://juronglakegardens.nparks.gov.sg/images/Fauna/changeable_lizard_male_crop_rt.jpg",
    width: 2341, height: 1560, name: "Changeable lizard",
    alt: "Male changeable lizard, NParks Jurong Lake Gardens reference photograph", photographer: "Ruth Tan / NParks",
    location: "NParks Jurong Lake Gardens reference photograph",
    sourceUrl: "https://juronglakegardens.nparks.gov.sg/reptiles-and-amphibians/", position: "50% 50%"
  },
  "asian-toad": {
    src: "https://isomer-user-content.by.gov.sg/283/d1ac93d5-2781-488a-a844-77cc14e95d6a/Common%20Asian%20Toad%20%282%29.jpg",
    width: 1920, height: 1080, name: "Asian toad",
    alt: "Common Asian toad, NParks BiodiversitySG reference photograph", photographer: "Raphael Moey / NParks BiodiversitySG",
    location: "NParks reference photograph",
    sourceUrl: "https://biodiversitysg.nparks.gov.sg/our-biodiversity/amphibians/common-asian-toad/", position: "50% 50%"
  },
  "sunda-colugo": {
    "src": "/wildlife/sunda-colugo.webp",
    "width": 1200,
    "height": 1500,
    "alt": "Sunda colugo gripping a tree trunk in Singapore's Central Catchment Nature Reserve",
    "name": "Sunda colugo",
    "location": "Central Catchment, Singapore",
    "date": "18 Jun 2006",
    "photographer": "Lip Kee Yap",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Colugo_(Galeopterus_variegatus,_adult_female),_Central_Catchment_Area,_Singapore_-_20060618.jpg",
    "position": "38% 20%"
  },
  "sunda-pangolin": {
    "src": "/wildlife/profiles/sunda-pangolin.webp",
    "width": 800,
    "height": 544,
    "alt": "Reference photograph of Sunda pangolin",
    "name": "Sunda pangolin",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Piekfrosch at German Wikipedia ( Original text: Piekfrosch (Wikipedia-User) )",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pangolin_borneo.jpg",
    "position": "50% 50%"
  },
  "mainland-leopard-cat": {
    "src": "/wildlife/profiles/mainland-leopard-cat.webp",
    "width": 1200,
    "height": 800,
    "alt": "Reference photograph of Mainland leopard cat",
    "name": "Mainland leopard cat",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Soumyajit Nandy",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Close-up_of_a_Leopard_Cat_in_Sundarban.jpg",
    "position": "50% 50%"
  },
  "smooth-coated-otter": {
    "src": "/wildlife/smooth-coated-otter.webp",
    "width": 1600,
    "height": 1067,
    "alt": "Two smooth-coated otters in water at Jurong Eco Garden, Singapore; one is eating a fish",
    "name": "Smooth-coated otter",
    "location": "Jurong Eco Garden, Singapore",
    "date": "2 Jul 2019",
    "photographer": "JJ Harrison",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lutrogale_perspicillata_-_Jurong_Eco_Garden.jpg",
    "position": "50% 50%"
  },
  "sunda-slow-loris": {
    "src": "/wildlife/profiles/sunda-slow-loris.webp",
    "width": 1200,
    "height": 800,
    "alt": "Reference photograph of Sunda slow loris",
    "name": "Sunda slow loris",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Lucie Čižmářová, The Kukang Rescue Program",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Outlo%C5%88_v%C3%A1hav%C3%BD_-_autor_Lucie_%C4%8Ci%C5%BEm%C3%A1%C5%99ov%C3%A1.jpg",
    "position": "50% 50%"
  },
  "oriental-pied-hornbill": {
    "src": "/wildlife/oriental-pied-hornbill.webp",
    "width": 900,
    "height": 1800,
    "alt": "Oriental pied hornbill with a pale bill and casque at Changi Beach Park, Singapore",
    "name": "Oriental pied hornbill",
    "location": "Changi Beach Park, Singapore",
    "date": "22 Jan 2019",
    "photographer": "JJ Harrison",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Anthracoceros_albirostris_-_Changi_Beach_Park.jpg",
    "position": "50% 17%"
  },
  "raffles-banded-langur": {
    "src": "/wildlife/profiles/raffles-banded-langur.webp",
    "width": 597,
    "height": 398,
    "alt": "Reference photograph of Raffles's banded langur",
    "name": "Raffles's banded langur",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Andie Ang",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Presbytis_femoralis_Andie_Ang.jpg",
    "position": "50% 50%"
  },
  "straw-headed-bulbul": {
    "src": "/wildlife/profiles/straw-headed-bulbul.webp",
    "width": 601,
    "height": 768,
    "alt": "Reference photograph of Straw-headed bulbul",
    "name": "Straw-headed bulbul",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Flickr user NatureAtYourBackyard . Photo uploaded to commons by user ltshears",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Straw_Headed_Bulbul.jpg",
    "position": "50% 50%"
  },
  "white-bellied-sea-eagle": {
    "src": "/wildlife/profiles/white-bellied-sea-eagle.webp",
    "width": 1200,
    "height": 800,
    "alt": "Reference photograph of White-bellied sea eagle",
    "name": "White-bellied sea eagle",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Manelka Jayasundara",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ceylon_Fish_Eagle_At_Yala_National_Park.jpg",
    "position": "50% 50%"
  },
  "hawksbill-turtle": {
    "src": "/wildlife/profiles/hawksbill-turtle.webp",
    "width": 1200,
    "height": 800,
    "alt": "Reference photograph of Hawksbill turtle",
    "name": "Hawksbill turtle",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Diego Delso",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tortuga_carey_(Eretmochelys_imbricata),_parque_nacional_Ras_Muhammad,_Egipto,_2022-03-28,_DD_56.jpg",
    "position": "50% 50%"
  },
  "green-turtle": {
    "src": "/wildlife/profiles/green-turtle.webp",
    "width": 1200,
    "height": 800,
    "alt": "Reference photograph of Green turtle",
    "name": "Green turtle",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Charles J. Sharp",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Green_sea_turtle_(Chelonia_mydas)_Moorea.jpg",
    "position": "50% 50%"
  },
  "estuarine-crocodile": {
    "src": "/wildlife/profiles/estuarine-crocodile.webp",
    "width": 1152,
    "height": 768,
    "alt": "Reference photograph of Estuarine crocodile",
    "name": "Estuarine crocodile",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Laubarr",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Laurie%27s_crocodile_in_the_garden.jpg",
    "position": "50% 50%"
  },
  "long-tailed-macaque": {
    "src": "/wildlife/profiles/long-tailed-macaque.webp",
    "width": 1200,
    "height": 1494,
    "alt": "Reference photograph of Long-tailed macaque",
    "name": "Long-tailed macaque",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Jakub Hałun",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Macaca_fascicularis,_Ubud_Monkey_Forest,_Bali,_20220822_1053_0059.jpg",
    "position": "50% 50%"
  },
  "plantain-squirrel": {
    "src": "/wildlife/profiles/plantain-squirrel.webp",
    "width": 1200,
    "height": 800,
    "alt": "Reference photograph of Plantain squirrel",
    "name": "Plantain squirrel",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Pangalau",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kundasang_War_Memorial_28_December_2023_12.jpg",
    "position": "50% 50%"
  },
  "sumatran-palm-civet": {
    "src": "/wildlife/profiles/sumatran-palm-civet.webp",
    "width": 1200,
    "height": 723,
    "alt": "Reference photograph of Sumatran palm civet",
    "name": "Sumatran palm civet",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Ian Dugdale",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Paradoxurus_musanga_(side).jpg",
    "position": "50% 50%"
  },
  "wild-boar": {
    "src": "/wildlife/profiles/wild-boar.webp",
    "width": 1200,
    "height": 800,
    "alt": "Reference photograph of Wild boar",
    "name": "Wild boar",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Valentin Panzirsch",
    "license": "CC BY-SA 3.0 at",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/at/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Wildschwein,_N%C3%A4he_Pulverstampftor.jpg",
    "position": "50% 50%"
  },
  "lesser-mousedeer": {
    "src": "/wildlife/profiles/lesser-mousedeer.webp",
    "width": 1200,
    "height": 1263,
    "alt": "Reference photograph of Lesser mousedeer",
    "name": "Lesser mousedeer",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Uspn (Bjørn Christian Tørrissen) .",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mouse-deer_Singapore_Zoo_2012.JPG",
    "position": "50% 50%"
  },
  "lesser-dog-faced-fruit-bat": {
    "src": "/wildlife/profiles/lesser-dog-faced-fruit-bat.webp",
    "width": 1024,
    "height": 768,
    "alt": "Reference photograph of Lesser dog-faced fruit bat",
    "name": "Lesser dog-faced fruit bat",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Simon J. Tonge",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cynopterus_brachyotis_three.jpeg",
    "position": "50% 50%"
  },
  "javan-myna": {
    "src": "/wildlife/profiles/javan-myna.webp",
    "width": 800,
    "height": 640,
    "alt": "Reference photograph of Javan myna",
    "name": "Javan myna",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Lip Kee Yap from Singapore, Republic of Singapore",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Javan_Myna_(Acridotheres_javanicus).jpg",
    "position": "50% 50%"
  },
  "house-crow": {
    "src": "/wildlife/profiles/house-crow.webp",
    "width": 1200,
    "height": 801,
    "alt": "Reference photograph of House crow",
    "name": "House crow",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Benjamint444",
    "license": "GFDL 1.2",
    "licenseUrl": "http://www.gnu.org/licenses/old-licenses/fdl-1.2.html",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:House-Crow444.jpg",
    "position": "50% 50%"
  },
  "asian-koel": {
    "src": "/wildlife/profiles/asian-koel.webp",
    "width": 1200,
    "height": 1730,
    "alt": "Reference photograph of Asian koel",
    "name": "Asian koel",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Challiyan",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Asian_koel.jpg",
    "position": "50% 50%"
  },
  "black-naped-oriole": {
    "src": "/wildlife/profiles/black-naped-oriole.webp",
    "width": 800,
    "height": 572,
    "alt": "Reference photograph of Black-naped oriole",
    "name": "Black-naped oriole",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Prof Dr Kamarudin Mat-Salleh (Flickr user: About Prof KMS (OTW to Borneo))",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Custardapplewithbird.jpg",
    "position": "50% 50%"
  },
  "collared-kingfisher": {
    "src": "/wildlife/profiles/collared-kingfisher.webp",
    "width": 1200,
    "height": 960,
    "alt": "Reference photograph of Collared kingfisher",
    "name": "Collared kingfisher",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "JJ Harrison ( https://www.jjharrison.com.au/ )",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Todiramphus_chloris_2_-_Laem_Phak_Bia.jpg",
    "position": "50% 50%"
  },
  "red-junglefowl": {
    "src": "/wildlife/profiles/red-junglefowl.webp",
    "width": 800,
    "height": 549,
    "alt": "Reference photograph of Red junglefowl",
    "name": "Red junglefowl",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Subramanya C K",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Red_jungle_fowl.png",
    "position": "50% 50%"
  },
  "malayan-water-monitor": {
    "src": "/wildlife/profiles/malayan-water-monitor.webp",
    "width": 1200,
    "height": 800,
    "alt": "Reference photograph of Malayan water monitor",
    "name": "Malayan water monitor",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Carlos Delgado",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Varanus_salvator_-_01.jpg",
    "position": "50% 50%"
  },
  "reticulated-python": {
    "src": "/wildlife/profiles/reticulated-python.webp",
    "width": 1200,
    "height": 1600,
    "alt": "Reference photograph of Reticulated python",
    "name": "Reticulated python",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Rina.saa",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Malayopython_reticulatus.jpg",
    "position": "50% 50%"
  },
  "equatorial-spitting-cobra": {
    "src": "/wildlife/profiles/equatorial-spitting-cobra.webp",
    "width": 350,
    "height": 467,
    "alt": "Reference photograph of Equatorial spitting cobra",
    "name": "Equatorial spitting cobra",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Nick Baker",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Equatrorial-spitting-cobra_001.jpg",
    "position": "50% 50%"
  },
  "common-house-gecko": {
    "src": "/wildlife/profiles/common-house-gecko.webp",
    "width": 1200,
    "height": 988,
    "alt": "Reference photograph of Common house gecko",
    "name": "Common house gecko",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Wikimedia Commons contributor",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hemidactylus_frenatus.jpg",
    "position": "50% 50%"
  },
  "banded-bullfrog": {
    "src": "/wildlife/profiles/banded-bullfrog.webp",
    "width": 720,
    "height": 480,
    "alt": "Reference photograph of Banded bullfrog",
    "name": "Banded bullfrog",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "The original uploader was Firereptiles at English Wikipedia .",
    "license": "Attribution",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:ChubbyFrog_02.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:ChubbyFrog_02.jpg",
    "position": "50% 50%"
  },
  "four-lined-tree-frog": {
    "src": "/wildlife/profiles/four-lined-tree-frog.webp",
    "width": 1200,
    "height": 788,
    "alt": "Reference photograph of Four-lined tree frog",
    "name": "Four-lined tree frog",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Brown R, Siler C, Oliveros C, Welton L, Rock A, Swab J, Van Weerd M, van Beijnen J, Rodriguez D, Jose E, Diesmos A",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Female_Polypedates_leucomystax_(KU_330233)_from_the_crater_of_Mt._Cagua_-_ZooKeys-266-001-g040.jpg",
    "position": "50% 50%"
  },
  "greater-mousedeer": {
    "src": "/wildlife/profiles/greater-mousedeer.webp",
    "width": 1200,
    "height": 800,
    "alt": "Reference photograph of Greater mousedeer",
    "name": "Greater mousedeer",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "The original uploader was Brian.gratwicke at English Wikipedia .",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tragulus_napu.jpg",
    "position": "50% 50%"
  },
  "malayan-porcupine": {
    "src": "/wildlife/profiles/malayan-porcupine.webp",
    "width": 369,
    "height": 249,
    "alt": "Reference photograph of Malayan porcupine",
    "name": "Malayan porcupine",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Modified from original source by User:Prashanthns",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hystrix_brachyura.JPG",
    "position": "50% 50%"
  },
  "horsfields-flying-squirrel": {
    "src": "/wildlife/profiles/horsfields-flying-squirrel.webp",
    "width": 1200,
    "height": 1952,
    "alt": "Reference photograph of Horsfield’s flying squirrel",
    "name": "Horsfield’s flying squirrel",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "John Gerrard Keulemans",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:SciuropterusDavisoniKeulemans.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:SciuropterusDavisoniKeulemans.jpg",
    "position": "50% 50%"
  },
  "red-cheeked-flying-squirrel": {
    "src": "/wildlife/profiles/red-cheeked-flying-squirrel.webp",
    "width": 1200,
    "height": 900,
    "alt": "Reference photograph of Red-cheeked flying squirrel",
    "name": "Red-cheeked flying squirrel",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "James Eaton",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hylopetes_spadiceus_339017647.jpg",
    "position": "50% 50%"
  },
  "small-toothed-palm-civet": {
    "src": "/wildlife/profiles/small-toothed-palm-civet.webp",
    "width": 1200,
    "height": 797,
    "alt": "Reference photograph of Small-toothed palm civet",
    "name": "Small-toothed palm civet",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Bernard DUPONT from FRANCE",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Small-toothed_Palm_Civet_(Arctogalidia_trivirgata_stigmatica)_(8076736823)_(cut).jpg",
    "position": "50% 50%"
  },
  "buffy-fish-owl": {
    "src": "/wildlife/profiles/buffy-fish-owl.webp",
    "width": 1200,
    "height": 1486,
    "alt": "Reference photograph of Buffy fish owl",
    "name": "Buffy fish owl",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Khan Mashuk Ahmed",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:%E0%A6%AE%E0%A7%87%E0%A6%9F%E0%A7%87_%E0%A6%AE%E0%A7%87%E0%A6%9B%E0%A7%8B%E0%A6%AA%E0%A7%8D%E0%A6%AF%E0%A6%BE%E0%A6%81%E0%A6%9A%E0%A6%BE(Bubo_ketupu)_%E0%A6%B8%E0%A7%81%E0%A6%A8%E0%A7%8D%E0%A6%A6%E0%A6%B0%E0%A6%AC%E0%A6%A8,%E0%A6%AC%E0%A6%BE%E0%A6%82%E0%A6%B2%E0%A6%BE%E0%A6%A6%E0%A7%87%E0%A6%B6%E0%A5%A4.jpg",
    "position": "50% 50%"
  },
  "blue-eared-kingfisher": {
    "src": "/wildlife/profiles/blue-eared-kingfisher.webp",
    "width": 1200,
    "height": 900,
    "alt": "Reference photograph of Blue-eared kingfisher",
    "name": "Blue-eared kingfisher",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Bernard DUPONT from FRANCE",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Blue-eared_Kingfisher_(Alcedo_meninting)_(8071061758).jpg",
    "position": "50% 50%"
  },
  "great-billed-heron": {
    "src": "/wildlife/profiles/great-billed-heron.webp",
    "width": 1200,
    "height": 800,
    "alt": "Reference photograph of Great-billed heron",
    "name": "Great-billed heron",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Wich’yanan (Jay) Limparungpatthanakij",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ardea_sumatrana_195843670.jpg",
    "position": "50% 50%"
  },
  "changeable-hawk-eagle": {
    "src": "/wildlife/profiles/changeable-hawk-eagle.webp",
    "width": 800,
    "height": 640,
    "alt": "Reference photograph of Changeable hawk-eagle",
    "name": "Changeable hawk-eagle",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Lip Kee from Singapore, Republic of Singapore",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Changeable_Hawk_eagle_-_Crested_Hawk-Eagle_-_Flickr_-_Lip_Kee.jpg",
    "position": "50% 50%"
  },
  "purple-heron": {
    "src": "/wildlife/profiles/purple-heron.webp",
    "width": 480,
    "height": 640,
    "alt": "Reference photograph of Purple heron",
    "name": "Purple heron",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Massimiliano.reggio",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:Ravenna_Ardea_Purpurea_2.JPG",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ravenna_Ardea_Purpurea_2.JPG",
    "position": "50% 50%"
  },
  "spiny-hill-turtle": {
    "src": "/wildlife/profiles/spiny-hill-turtle.webp",
    "width": 1200,
    "height": 900,
    "alt": "Reference photograph of Spiny hill turtle",
    "name": "Spiny hill turtle",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Justin Philbois",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Heosemys_spinosa_390638960.jpg",
    "position": "50% 50%"
  },
  "asian-leaf-turtle": {
    "src": "/wildlife/profiles/asian-leaf-turtle.webp",
    "width": 800,
    "height": 741,
    "alt": "Reference photograph of Asian leaf turtle",
    "name": "Asian leaf turtle",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Wibowo Djatmiko ( Wie146 )",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cycle_denta_100207-0641_ipb.jpg",
    "position": "50% 50%"
  },
  "clouded-monitor": {
    "src": "/wildlife/profiles/clouded-monitor.webp",
    "width": 1200,
    "height": 900,
    "alt": "Reference photograph of Clouded monitor",
    "name": "Clouded monitor",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Nils",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Varanus_nebulosus_291947376.jpg",
    "position": "50% 50%"
  },
  "grey-heron": {
    "src": "/wildlife/profiles/grey-heron.webp",
    "width": 1200,
    "height": 900,
    "alt": "Reference photograph of Grey heron",
    "name": "Grey heron",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Bengt Nyman from Vaxholm, Sweden",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ardea_cinerea_EM1A2714_(27349354381).jpg",
    "position": "50% 50%"
  },
  "little-egret": {
    "src": "/wildlife/profiles/little-egret.webp",
    "width": 1200,
    "height": 795,
    "alt": "Reference photograph of Little egret",
    "name": "Little egret",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "El Golli Mohamed",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Aigrette_garzette_au_lac_sud_de_Tunis_(site_RAMSAR).jpg",
    "position": "50% 50%"
  },
  "malayan-horned-frog": {
    "src": "/wildlife/profiles/malayan-horned-frog.webp",
    "width": 895,
    "height": 401,
    "alt": "Reference photograph of Malayan horned frog",
    "name": "Malayan horned frog",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Haas A, Boon-Hee K, Joseph A, bin Asri M, Das I, Hagmann R, Schwander L, Hertwig ST (2018) An updated checklist of the amphibian diversity of Maliau Basin Conservation Area, Sabah, Malaysia. Evolutionary Systematics 2: 89-114. https://doi.org/10.3897/evolsyst.2.27020",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Megophrys_nasuta_(10.3897-evolsyst.2.27020)_Figure_2_(cropped).jpg",
    "position": "50% 50%"
  },
  "dugong": {
    "src": "/wildlife/profiles/dugong.webp",
    "width": 1200,
    "height": 900,
    "alt": "Reference photograph of Dugong",
    "name": "Dugong",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "Julien Willem",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dugong_Marsa_Alam.jpg",
    "position": "50% 50%"
  },
  "indo-pacific-humpback-dolphin": {
    "src": "/wildlife/profiles/indo-pacific-humpback-dolphin.webp",
    "width": 1200,
    "height": 900,
    "alt": "Reference photograph of Indo-Pacific humpback dolphin",
    "name": "Indo-Pacific humpback dolphin",
    "location": "Wikimedia Commons reference photograph",
    "photographer": "user:takoradee",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pink_Dolphin.JPG",
    "position": "50% 50%"
  },
  "black-eyed-litter-frog": {
    "src": "/wildlife/profiles/black-eyed-litter-frog.webp",
    "width": 1200,
    "height": 1600,
    "alt": "Reference photograph of Black-eyed litter frog",
    "name": "Black-eyed litter frog",
    "location": "GBIF occurrence reference photograph",
    "photographer": "Cara-Lisa Schloots",
    "license": "CC BY",
    "licenseUrl": "http://creativecommons.org/licenses/by/4.0/",
    "sourceUrl": "https://www.gbif.org/occurrence/6413844541",
    "position": "50% 50%"
  },
  "irrawaddy-dolphin": {
    src: "https://www.wwf.or.jp/image/Sub1_rev.jpg",
    width: 1200, height: 800,
    alt: "Reference photograph of an Irrawaddy dolphin",
    name: "Irrawaddy dolphin", location: "Myanmar waters reference photograph",
    photographer: "WWF Japan; see source",
    sourceUrl: "https://www.wwf.or.jp/press/5952.html",
    position: "50% 50%",
  },
  "false-killer-whale": {
    src: "/wildlife/profiles/false-killer-whale.jpg",
    width: 800, height: 640,
    alt: "False killer whale surfacing in the sea, NOAA reference photograph",
    name: "False killer whale", location: "Species reference photograph",
    photographer: "NOAA / Southwest Fisheries Science Center",
    license: "Public domain",
    licenseUrl: "https://commons.wikimedia.org/wiki/File:False_killer_whale_890002.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:False_killer_whale_890002.jpg",
    position: "50% 50%",
  },
  "indo-pacific-bottlenose-dolphin": {
    src: "https://upload.wikimedia.org/wikipedia/commons/8/87/Tursiops_aduncus%2C_Port_River%2C_Adelaide%2C_Australia_-_2003.jpg",
    width: 1200, height: 800,
    alt: "Reference photograph of an Indo-Pacific bottlenose dolphin",
    name: "Indo-Pacific bottlenose dolphin", location: "Port River, Adelaide, Australia",
    photographer: "Wikimedia Commons contributor",
    license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tursiops_aduncus,_Port_River,_Adelaide,_Australia_-_2003.jpg",
    position: "50% 50%",
  },
  "indo-pacific-finless-porpoise": {
    src: "https://www.nhptv.org/wild/images/finlessporpoise.jpg",
    width: 1200, height: 800,
    alt: "Reference photograph of an Indo-Pacific finless porpoise",
    name: "Indo-Pacific finless porpoise", location: "Species reference photograph",
    photographer: "New Hampshire PBS Wildlife Journal",
    sourceUrl: "https://www.nhptv.org/wild/phocoenidae.asp",
    position: "50% 50%",
  },
  "sperm-whale": {
    src: "https://marilles.org/storage/media/2022/12/1581/d080479-at-jordichias.jpg",
    width: 1200, height: 800,
    alt: "Reference photograph of a Sperm whale",
    name: "Sperm whale", location: "Mediterranean reference photograph",
    photographer: "Jordi Chías",
    sourceUrl: "https://marilles.org/en/post/cachalotes-desprotegidos",
    position: "50% 50%",
  },
  "common-treeshrew": {
    src: "/wildlife/profiles/common-treeshrew.jpg",
    width: 1800, height: 1200,
    alt: "Common treeshrew on a moss-covered log, reference photograph",
    name: "Common treeshrew", location: "Thailand · species reference photograph",
    photographer: "Wich’yanan L",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tupaia_glis_306726877.jpg",
    position: "50% 50%",
  },
  "cave-nectar-bat": {
    src: "https://www.merlintuttle.org/wp-content/uploads/2015/04/MDT_TH4_C3_6885.jpg",
    width: 1200, height: 800,
    alt: "Reference photograph of a Cave nectar bat",
    name: "Cave nectar bat", location: "Species reference photograph",
    photographer: "Merlin Tuttle",
    sourceUrl: "https://www.merlintuttle.org/documenting-billion-dollar-bats/",
    position: "50% 50%",
  },
  "lesser-long-tongued-nectar-bat": {
    src: "https://inaturalist-open-data.s3.amazonaws.com/photos/254533/original.jpg",
    width: 1200, height: 800,
    alt: "Reference photograph of a Lesser long-tongued nectar bat",
    name: "Lesser long-tongued nectar bat", location: "Species reference photograph",
    photographer: "Chien Lee",
    license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://www.inaturalist.org/taxa/40946-Macroglossus-minimus",
    position: "50% 50%",
  },
  "large-flying-fox": {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Pteropus_vampyrus_435399917.jpg/1280px-Pteropus_vampyrus_435399917.jpg",
    width: 1280, height: 853,
    alt: "Reference photograph of a Large flying fox",
    name: "Large flying fox", location: "Species reference photograph",
    photographer: "Justin Philbois",
    license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pteropus_vampyrus_435399917.jpg",
    position: "50% 50%",
  },
  "asian-small-clawed-otter": {
    src: "https://www.hkzbg.gov.hk/assets/images/animals/cover/Mammals/Asian_small_clawed_otter.jpg",
    width: 1200, height: 800,
    alt: "Reference photograph of an Asian small-clawed otter",
    name: "Asian small-clawed otter", location: "Hong Kong Zoological and Botanical Gardens reference photograph",
    photographer: "Hong Kong Zoological and Botanical Gardens",
    sourceUrl: "https://www.hkzbg.gov.hk/en/animals/mammals/animals_15.html",
    position: "50% 50%",
  },
  ...Object.fromEntries((fullBirdProfiles as Array<{ id: string; name: string; photo: { src: string; alt: string; photographer: string; sourceUrl: string } | null }>).flatMap((bird) => bird.photo ? [[bird.id, {
    src: bird.photo.src,
    width: 400,
    height: 300,
    alt: bird.photo.alt,
    name: bird.name,
    location: "Bird Society of Singapore reference photograph",
    photographer: bird.photo.photographer,
    sourceUrl: bird.photo.sourceUrl,
    position: "50% 50%",
  } satisfies WildlifePhotoRecord]] : [])),
};
