export type AnimalGroup = "Mammal" | "Bird" | "Reptile" | "Amphibian";
export type ProfileSource = { name: string; url: string; supports: string };
export type AnimalProfile = {
  id: string;
  group: AnimalGroup;
  family: string;
  aliases: string[];
  tags?: string[];
  origin: "Native" | "Introduced";
  encounter: "Commonly seen" | "Elusive" | "Rare or restricted";
  habitats: string[];
  summary: string;
  identification: string;
  diet: string;
  activity: string;
  behaviour: string;
  reproduction: string;
  singapore: string;
  ecologicalRole: string;
  pressures: string;
  watch: string;
  funFacts: { title: string; text: string; sourceUrl?: string }[];
  sources: ProfileSource[];
  taxonomyNote?: string;
  statusNote?: string;
  photo?: "colugo" | "otter" | "hornbill";
};

const adw = (taxon: string, supports = "Life history and reproduction"): ProfileSource => ({ name: "Animal Diversity Web · University of Michigan", url: `https://animaldiversity.org/accounts/${taxon}/`, supports });
const np = (url: string, supports = "Identification and ecology"): ProfileSource => ({
  name: url.includes("/florafaunaweb/") ? "NParks · Flora & Fauna Web" : url.includes("biodiversitysg.nparks.gov.sg") ? "NParks · BiodiversitySG" : url.includes("juronglakegardens.nparks.gov.sg") ? "NParks · Jurong Lake Gardens" : url.includes("/nature/species-list/") ? "NParks · Singapore species list" : "NParks · wildlife reference",
  url, supports,
});
const avs = (slug: string): ProfileSource => ({ name: "NParks / AVS · living with wildlife", url: `https://avs.nparks.gov.sg/wildlife/encountering-wildlife/${slug}/`, supports: "Safe encounters and coexistence" });

/** Original learning summaries. National assessments are joined in species-data.ts.
 * Encounter groups are qualitative editorial summaries, never population estimates.
 * Each profile also inherits its primary NParks record as a source.
 */
export const ANIMAL_PROFILES: Record<string, AnimalProfile> = {
  "Galeopterus variegatus": {
    id: "sunda-colugo", group: "Mammal", family: "Cynocephalidae", aliases: ["Malayan flying lemur", "flying lemur"], origin: "Native", encounter: "Elusive", habitats: ["Forest", "Parks"], photo: "colugo",
    summary: "A tree specialist that travels on a sheet of skin. Colugos glide between trunks instead of flapping wings, and spend much of the day pressed quietly against bark.",
    identification: "Look for mottled grey-brown fur, large eyes, curved claws and a broad membrane joining the limbs and tail. The folded membrane can be hard to see on a resting animal.",
    diet: "Young leaves, shoots, flowers and fruit.", activity: "Mainly nocturnal; rests on trees by day.",
    behaviour: "Climbs to gain height before a glide. Camouflage and stillness help it stay unnoticed. It is neither a bat nor a true lemur.",
    reproduction: "Usually one young is born. The infant clings to its mother; she can fold her gliding membrane around it for support and warmth.",
    singapore: "Associated with tall forest in the Central Nature Reserves and connected wooded spaces. A quiet, hidden animal may be present even when visitors do not notice it.",
    ecologicalRole: "A canopy herbivore that links plant growth to the forest food web.",
    pressures: "Loss of connected tree cover reduces feeding areas and routes through the canopy.",
    watch: "Stay on open trails. Use binoculars and avoid flash or shining a light into its eyes.",
    funFacts: [{ title: "A blanket that glides", text: "A mother can fold her gliding membrane into a pouch around her young.", sourceUrl: "https://animaldiversity.org/accounts/Galeopterus_variegates/" }, { title: "Flying in name only", text: "The ‘flying lemur’ is neither a lemur nor a powered flier." }],
    sources: [adw("Galeopterus_variegates")],
  },
  "Manis javanica": {
    id: "sunda-pangolin", group: "Mammal", family: "Manidae", aliases: ["scaly anteater"], origin: "Native", encounter: "Rare or restricted", habitats: ["Forest", "Parks"],
    summary: "Singapore’s native pangolin is a shy, scale-covered mammal. It searches for social insects on the ground and in trees, using strong claws and a long sticky tongue.",
    identification: "Overlapping brown scales, a narrow head, a long tail and powerful digging claws. Its underside has softer skin and hair.",
    diet: "Ants and termites; it opens their nests to reach them.", activity: "Mostly nocturnal and secretive.",
    behaviour: "Can climb trees as well as walk on the ground. When frightened it rolls up, protecting its softer underside with scales.",
    reproduction: "Usually has one baby at a time. Young may ride on the mother’s tail or back while she moves.",
    singapore: "Recorded in forested areas, including the Central Catchment and offshore islands. Exact resting sites are deliberately excluded from this guide.",
    ecologicalRole: "A specialised predator of ants and termites within forest food webs.",
    pressures: "Road collisions and habitat loss matter locally. Wildlife trafficking is a major threat across its wider range.",
    watch: "Give it a clear escape route. Do not touch, corner or pick it up; contact AVS if it is injured or trapped.",
    funFacts: [{ title: "A tiny passenger", text: "A young pangolin can hitch a ride on its mother’s back or tail.", sourceUrl: "https://biodiversitysg.nparks.gov.sg/our-biodiversity/mammals/other-mammals/sunda-pangolin/" }, { title: "Built-in protection", text: "Its defensive curl puts tough scales outside and its soft belly inside.", sourceUrl: "https://biodiversitysg.nparks.gov.sg/our-biodiversity/mammals/other-mammals/sunda-pangolin/" }],
    sources: [np("https://biodiversitysg.nparks.gov.sg/our-biodiversity/mammals/other-mammals/sunda-pangolin/", "Diet, young, behaviour and local threats"), avs("pangolins")],
  },
  "Prionailurus bengalensis": {
    id: "mainland-leopard-cat", group: "Mammal", family: "Felidae", aliases: ["leopard cat"], origin: "Native", encounter: "Rare or restricted", habitats: ["Forest", "Scrub"],
    summary: "A small wild cat with a spotted coat, rather than a miniature leopard. This quiet hunter uses forest, scrub and plantations and can be difficult to distinguish in a brief night-time glimpse.",
    identification: "Yellowish or reddish-buff fur with dark spots; rounded ears have pale spots on their black backs. It has a short muzzle and rounded head.",
    diet: "Small vertebrates such as rodents, frogs, lizards and birds.", activity: "Mostly nocturnal.",
    behaviour: "Often solitary. Hunts mainly on the ground but is an able climber. A single photograph may not be enough to rule out a domestic cat.",
    reproduction: "Females raise dependent kittens in sheltered dens. The regional literature describes small litters; this is not a Singapore breeding forecast.",
    singapore: "NParks documents records from wooded areas on the mainland and offshore islands. These scattered records do not imply that all such places hold resident populations.",
    ecologicalRole: "A small predator within the forest food web, including predators of rodents.",
    pressures: "Habitat loss and possible illegal trapping are identified in the NParks profile.",
    watch: "Do not pursue it or disclose a den location. Report suspected trapping to the relevant wildlife authority.",
    funFacts: [{ title: "Spots behind the ears", text: "The back of each rounded ear carries a pale spot against black fur." }, { title: "Ground hunter, tree climber", text: "Although it hunts mainly on land, this cat can climb trees with ease." }],
    sources: [adw("Prionailurus_bengalensis")],
  },
  "Lutrogale perspicillata": {
    id: "smooth-coated-otter", group: "Mammal", family: "Mustelidae", aliases: ["smooth otter"], origin: "Native", encounter: "Commonly seen", habitats: ["Freshwater", "Mangrove", "Parks"], photo: "otter",
    summary: "A social water-loving mammal that has returned to Singapore’s waterways. Family groups can live close to people, but they still need space to feed, rest and raise pups.",
    identification: "A long brown body, short smooth fur and a paler throat and underside. It is larger than the Asian small-clawed otter; do not identify the species from size alone.",
    diet: "Mainly fish, with other aquatic prey.", activity: "Active on land and in water; sightings vary with the group and site.",
    behaviour: "Travels and feeds in family groups. Groups use scent and calls and may compete with other families over territory.",
    reproduction: "Pups are raised in sheltered dens, with adults attending them. Keep away from resting and den areas even if no adult is visible.",
    singapore: "Uses mangroves, reservoirs, ponds and urban canals. Frequent sightings at one waterway do not change its national Endangered status.",
    ecologicalRole: "An aquatic predator connecting waterways and adjacent land habitats.",
    pressures: "Road crossings, disturbance and unsafe encounters can affect urban families. Connected, usable waterways remain important.",
    watch: "Keep your distance and do not block the route between the group and water. Keep dogs leashed and never feed otters.",
    funFacts: [{ title: "Family travellers", text: "Several generations can share a family group and move along waterways together.", sourceUrl: "https://avs.nparks.gov.sg/wildlife/encountering-wildlife/otters/" }, { title: "A city comeback", text: "Singapore now has breeding otter families using urban as well as natural waterways." }],
    sources: [avs("otters"), adw("Lutrogale_perspicillata", "Social behaviour and life history")],
  },
  "Nycticebus coucang": {
    id: "sunda-slow-loris", group: "Mammal", family: "Lorisidae", aliases: ["slow loris"], origin: "Native", encounter: "Rare or restricted", habitats: ["Forest"],
    summary: "A nocturnal primate that moves carefully through branches. Its deliberate movement, strong grip and large eyes suit a life in the dark canopy.",
    identification: "Rounded head, large forward-facing eyes, dense fur and a dark stripe along the back. The tail is very short and usually hidden.",
    diet: "Tree gums and sap, nectar and small animal prey including insects.", activity: "Nocturnal; rests out of sight during daylight.",
    behaviour: "Moves hand over hand and can hold branches for long periods. A slow movement style does not make it safe to handle: it has a venomous bite.",
    reproduction: "Females usually produce a single infant and provide prolonged care. Young depend on their mother before foraging independently.",
    singapore: "A rare forest resident recorded in the nature reserves and Pulau Tekong. This guide withholds precise observation and resting locations.",
    ecologicalRole: "Feeds across plant and small-animal parts of the canopy food web.",
    pressures: "Habitat loss and the illegal pet trade affect slow lorises. Connected forest and freedom from disturbance are important.",
    watch: "Never touch or attempt to rescue one by hand. Do not use flash photography or lure it into view.",
    funFacts: [{ title: "A surprising primate", text: "The slow loris is venomous; its gentle appearance does not mean it is safe to handle." }, { title: "Branch by branch", text: "Strong hands and feet let it move carefully through the canopy without big leaps." }],
    sources: [adw("Nycticebus_coucang")],
  },
  "Presbytis femoralis": {
    id: "raffles-banded-langur", group: "Mammal", family: "Cercopithecidae", aliases: ["banded leaf monkey", "banded langur"], origin: "Native", encounter: "Rare or restricted", habitats: ["Forest"],
    summary: "One of Singapore’s rarest primates, this leaf-eating monkey depends on mature forest. It is different from the more familiar long-tailed macaque seen at forest edges.",
    identification: "Mostly dark fur, a long tail and contrasting pale areas on the underside and inner limbs. Observe the whole pattern and body shape from a distance.",
    diet: "Leaves, unripe fruit and other plant material.", activity: "Mainly active during daylight in the canopy.",
    behaviour: "Lives in social groups and spends much of its time in trees. Its specialised stomach supports digestion of leafy food.",
    reproduction: "Infants have a much paler coat than adults and depend on maternal care. Their colouring changes as they grow.",
    singapore: "The local population is very small and concentrated in the Central Catchment. The species also occurs in southern Peninsular Malaysia.",
    ecologicalRole: "A forest canopy herbivore, linked to the diversity of its food plants.",
    pressures: "Small population size and fragmented forest make protection of habitat and connectivity important.",
    watch: "Use open trails and binoculars. Do not follow a group off-trail, play calls or share sensitive locations.",
    funFacts: [{ title: "A change of coat", text: "Young langurs start much paler than the dark adults and change colour as they grow." }, { title: "Leaf specialist", text: "A multi-chambered stomach helps it process fibrous plant food." }],
    sources: [np("https://www.nparks.gov.sg/nature/species-list/terrestrial-mammals", "Singapore origin, name and RDB3 status")],
  },
  "Pycnonotus zeylanicus": {
    id: "straw-headed-bulbul", group: "Bird", family: "Pycnonotidae", aliases: [], origin: "Native", encounter: "Rare or restricted", habitats: ["Forest", "Freshwater", "Scrub"],
    summary: "A large songbird whose voice often gives it away before its body appears. Singapore is important to its survival, while capture for the songbird trade has damaged populations elsewhere.",
    identification: "A straw-coloured crown, dark facial stripes and pale streaks on the breast. It is larger than many familiar urban bulbuls.",
    diet: "Fruit, berries and insects.", activity: "Diurnal; often heard from dense vegetation.",
    behaviour: "Forages in thick foliage near water and forest edges. Its loud, bubbling song is a useful clue, but listening must not become playback or disturbance.",
    reproduction: "An egg-laying bird whose nesting cover needs protection. Do not seek nests or publish nest locations; local timing is not predicted by this guide.",
    singapore: "Found in suitable wooded habitats, including Pulau Ubin. Local occurrence and its global Critically Endangered label refer to different geographic scales.",
    ecologicalRole: "A fruit-eater and insect predator within wooded habitats.",
    pressures: "Illegal capture for the songbird trade and habitat loss. Singapore’s species action plan includes habitat work and protection against poaching.",
    watch: "Listen quietly from paths. Never play calls to draw it out, set up bait or publicise a nest.",
    funFacts: [{ title: "Heard before seen", text: "Its bubbling song can reveal a bird that stays hidden in dense leaves." }, { title: "A big bulbul", text: "NParks describes it as Singapore’s largest bulbul species." }],
    sources: [],
  },
  "Anthracoceros albirostris": {
    id: "oriental-pied-hornbill", group: "Bird", family: "Bucerotidae", aliases: ["pied hornbill"], origin: "Native", encounter: "Commonly seen", habitats: ["Forest", "Parks", "Mangrove"], photo: "hornbill",
    summary: "A conspicuous black-and-white bird with a pale bill and a raised casque. Its return to Singapore is a conservation story linked to suitable habitat and nesting places.",
    identification: "Large pale bill, casque above the bill, black wings and upperparts, and a white belly. Look at several features rather than comparing it with a toucan.",
    diet: "Mainly fruit, supplemented by small animals.", activity: "Diurnal; calls and travels through wooded areas.",
    behaviour: "Visits fruiting trees and may travel in pairs or groups. Tree cavities are essential for its unusual nesting routine.",
    reproduction: "The female and chicks stay in a mostly sealed cavity. The male brings food through a narrow opening.",
    singapore: "Now found in suitable parks and wooded areas, including Pulau Ubin. Recovery does not make every site suitable for nesting.",
    ecologicalRole: "Fruit consumption can move seeds between patches of vegetation.",
    pressures: "Loss of large cavity-bearing trees and disturbance at nests. Nest boxes have supported local conservation efforts.",
    watch: "Leave fruit for wildlife. Do not feed, crowd or approach a nesting cavity.",
    funFacts: [{ title: "Room service in a tree", text: "The male delivers meals through the small entrance of the sealed nest." }, { title: "A bill with a helmet", text: "The raised structure on top of the bill is called a casque." }],
    sources: [],
  },
  "Haliaeetus leucogaster": {
    id: "white-bellied-sea-eagle", group: "Bird", family: "Accipitridae", aliases: ["sea eagle", "Icthyophaga leucogaster"], origin: "Native", encounter: "Commonly seen", habitats: ["Coast", "Freshwater"],
    summary: "A large coastal raptor often seen circling above Singapore’s water. Adult and young birds look quite different, so a brown eagle is not automatically another species.",
    identification: "Adults have a white head and underside with grey upperparts. Young birds are mottled brown. Broad wings are held in a shallow V when soaring.",
    diet: "Fish and other animals taken around waterways; also scavenges.", activity: "Diurnal, often soaring above water.",
    behaviour: "Uses rising air to soar while looking for food. Pairs build large stick nests in suitable tall trees.",
    reproduction: "Both adults help with nesting and care for chicks. Nests may be reused and enlarged over successive years.",
    singapore: "Occurs around reservoirs, rivers and the coast. It can be observed from many public waterfronts without approaching a nest.",
    ecologicalRole: "A high-level predator and scavenger associated with aquatic food webs.",
    pressures: "Protecting large nesting trees and limiting disturbance helps keep suitable habitat available.",
    watch: "Use binoculars from a safe viewpoint. Never fly a drone near a nest or move closer to force a take-off.",
    funFacts: [{ title: "A growing home", text: "A pair can keep adding sticks to a nest that it uses again." }, { title: "A different youngster", text: "Brown juvenile plumage changes gradually into the adult white-and-grey pattern." }],
    sources: [], taxonomyNote: "The display name follows the linked NParks profile; some bird checklists use Icthyophaga leucogaster.",
  },
  "Eretmochelys imbricata": {
    id: "hawksbill-turtle", group: "Reptile", family: "Cheloniidae", aliases: ["hawksbill sea turtle"], origin: "Native", encounter: "Rare or restricted", habitats: ["Coast", "Reef"],
    summary: "A sea turtle associated with tropical reefs. Its narrow, hooked beak reaches into crevices, while adult females depend on suitable beaches to lay eggs.",
    identification: "A pointed beak and overlapping shell scutes distinguish typical hawksbills from green turtles. Keep a distance; do not handle a turtle to inspect its shell.",
    diet: "Often sponges, with other reef animals also eaten.", activity: "Marine; females come ashore to nest, usually at night.",
    behaviour: "Forages around reef habitat and returns to the surface to breathe. It cannot stay underwater indefinitely.",
    reproduction: "Females bury eggs in sand. Hatchlings move toward the sea; people and artificial light can disrupt this vulnerable journey.",
    singapore: "Recorded in local waters and nesting on Singapore shores. A nesting record is not a reliable count of the local population.",
    ecologicalRole: "A reef consumer, especially of sponges, within marine food webs.",
    pressures: "Fishing-gear entanglement, loss or disturbance of beaches, pollution and the international tortoiseshell trade.",
    watch: "Keep lights and flash off near nesting turtles. Do not touch adults, eggs or hatchlings; follow NParks’ reporting guidance.",
    funFacts: [{ title: "Roof tiles on a shell", text: "The shell’s overlapping scutes are a useful hawksbill identification feature.", sourceUrl: "https://www.fisheries.noaa.gov/species/hawksbill-turtle" }, { title: "A reef toolkit", text: "Its narrow beak helps reach food tucked into reef crevices.", sourceUrl: "https://www.fisheries.noaa.gov/species/hawksbill-turtle" }],
    sources: [{ name: "NOAA Fisheries · hawksbill turtle", url: "https://www.fisheries.noaa.gov/species/hawksbill-turtle", supports: "Identification, diet, life cycle and threats" }, avs("hawksbill-turtles")],
  },
  "Chelonia mydas": {
    id: "green-turtle", group: "Reptile", family: "Cheloniidae", aliases: ["green sea turtle"], origin: "Native", encounter: "Rare or restricted", habitats: ["Coast", "Reef", "Seagrass"],
    summary: "A marine turtle that uses tropical and subtropical seas. Adults often graze shallow feeding grounds, while nesting requires accessible sandy beaches.",
    identification: "An oval shell with non-overlapping scutes, paddle-like flippers and one pair of scales between the eyes. The shell is usually brownish, not bright green.",
    diet: "Adults mainly eat seagrasses and algae; diet changes with life stage.", activity: "Lives at sea and surfaces for air; nesting is mainly nocturnal.",
    behaviour: "Moves between feeding grounds and nesting areas. Its strong front flippers provide propulsion in the water.",
    reproduction: "Females dig nests in sandy beaches and bury their eggs. Hatchlings face a separate early life at sea without parental care.",
    singapore: "Recorded in the Singapore Straits. Protecting coastal feeding habitat and nesting beaches supports turtles moving through the wider region.",
    ecologicalRole: "An important grazer in some seagrass and algal habitats.",
    pressures: "Fishing gear, marine pollution, coastal habitat loss and disturbance of nesting beaches.",
    watch: "Do not block a turtle’s route or use bright lights around nests. Observe from a distance and report nesting to NParks.",
    funFacts: [{ title: "Green, but not its shell", text: "Its common name refers to greenish body fat, rather than a green shell.", sourceUrl: "https://www.fisheries.noaa.gov/species/green-turtle" }, { title: "A changing menu", text: "Young green turtles eat more animal food than the mostly plant-eating adults.", sourceUrl: "https://www.fisheries.noaa.gov/species/green-turtle" }],
    sources: [{ name: "NOAA Fisheries · green turtle", url: "https://www.fisheries.noaa.gov/species/green-turtle", supports: "Life stages, feeding, breeding and threats" }], statusNote: "The older NParks profile shows a historical global Endangered label. The linked 2025 IUCN assessment is Least Concern globally; Singapore RDB3 remains Critically Endangered.",
  },
  "Crocodylus porosus": {
    id: "estuarine-crocodile", group: "Reptile", family: "Crocodylidae", aliases: ["saltwater crocodile"], origin: "Native", encounter: "Rare or restricted", habitats: ["Mangrove", "Coast", "Freshwater"],
    summary: "A large native reptile of estuaries and wetlands. Crocodiles can be difficult to detect in water; viewing must be from designated safe areas.",
    identification: "Broad snout, armoured body and a muscular, flattened tail. Only the eyes and nostrils may show above the surface.",
    diet: "Fish and other animals; also scavenges.", activity: "Often basks by day and hunts mainly at night.",
    behaviour: "Spends time concealed in water or vegetation. Adults may use freshwater as well as saline habitats despite the name ‘saltwater crocodile’.",
    reproduction: "The female lays eggs in a vegetation nest and guards it. A concealed nest area must never be approached.",
    singapore: "Recorded from northern wetlands and estuaries, including Sungei Buloh. Records are not an invitation to approach water edges outside permitted areas.",
    ecologicalRole: "A large wetland predator and scavenger.",
    pressures: "Loss of estuarine habitat and conflict with people. Keeping safe separation protects visitors and wildlife.",
    watch: "Follow park warnings and stay on designated paths. Keep well away from water edges, do not feed, and alert park staff to unsafe encounters.",
    funFacts: [{ title: "Not just salt water", text: "Despite one of its names, it also uses freshwater habitats." }, { title: "A guarded nursery", text: "The female builds a vegetation nest and guards the eggs." }],
    sources: [avs("crocodiles")],
  },
  "Macaca fascicularis": {
    id: "long-tailed-macaque", group: "Mammal", family: "Cercopithecidae", aliases: ["crab-eating macaque", "monkey"], origin: "Native", encounter: "Commonly seen", habitats: ["Forest", "Mangrove", "Parks"],
    summary: "Singapore’s familiar forest-edge monkey is a social, adaptable native primate. Food left accessible by people can draw groups into close contact with visitors and homes.",
    identification: "Brown-grey coat, relatively pale underside and a tail that can be as long as the head and body together. It differs from the dark, pale-banded langur.",
    diet: "Fruit and other plant food, plus insects and other small animals.", activity: "Mainly diurnal.",
    behaviour: "Lives in groups organised around related females. It forages both in trees and on the ground and uses calls, expressions and grooming socially.",
    reproduction: "Usually gives birth to one infant. Mothers carry and nurse young, which remain within the social group as they grow.",
    singapore: "Commonly encountered in and around forest reserves and some parkland. Feeding changes natural foraging behaviour and increases conflict.",
    ecologicalRole: "An omnivore and fruit consumer in forest food webs.",
    pressures: "Food-conditioned behaviour, unsafe interactions and habitat fragmentation can create local problems, even for a nationally Least Concern species.",
    watch: "Keep food out of sight, secure bags and give the group space. Do not stare, feed, tease or try to touch a monkey.",
    funFacts: [{ title: "A long balancing act", text: "Its tail can rival the combined length of its head and body." }, { title: "Family connections", text: "Groups are organised around female family lines." }],
    sources: [adw("Macaca_fascicularis"), avs("macaques")],
  },
  "Callosciurus notatus": {
    id: "plantain-squirrel", group: "Mammal", family: "Sciuridae", aliases: ["squirrel"], origin: "Native", encounter: "Commonly seen", habitats: ["Forest", "Parks", "Urban"],
    summary: "A familiar squirrel of Singapore’s trees and gardens. It spends daylight hours searching for food and moving quickly between trunks and branches.",
    identification: "A bushy tail and a pale stripe above a darker stripe on each flank are useful clues. Check side markings, rather than relying on coat colour alone.",
    diet: "Fruit, seeds and other plant food, with some animal food.", activity: "Diurnal.",
    behaviour: "Uses claws to climb and makes quick leaps between branches. Chirps and chatter are part of its communication.",
    reproduction: "Young are born in a sheltered nest and depend on their mother. Leave leafy nests undisturbed even when they appear empty.",
    singapore: "NParks describes it as the most common squirrel in local urban parks and gardens. It also uses forest and other wooded habitats.",
    ecologicalRole: "A seed and fruit consumer within tree-based food webs.",
    pressures: "Loss of tree connections and feeding by people can affect normal movement and foraging.",
    watch: "Enjoy it from the path. Do not bait it for a photograph or offer snacks.",
    funFacts: [{ title: "A chatty neighbour", text: "Listen for loud chirps and chatter while squirrels move among branches." }, { title: "Read the stripes", text: "The contrasting stripes along its flanks help separate it from other squirrels.", sourceUrl: "https://animaldiversity.org/accounts/Callosciurus_notatus/" }],
    sources: [adw("Callosciurus_notatus", "Identification, food and nesting")],
  },
  "Paradoxurus musangus": {
    id: "sumatran-palm-civet", group: "Mammal", family: "Viverridae", aliases: ["common palm civet", "Asian palm civet", "musang", "toddy cat"], origin: "Native", encounter: "Elusive", habitats: ["Forest", "Parks", "Urban"],
    summary: "A nocturnal fruit-eater and small-animal hunter, often known locally as the common palm civet. It can move through both trees and settled areas in search of food.",
    identification: "A long body and tail, pointed muzzle and dark facial markings. It is a civet, not a domestic cat despite the nickname ‘toddy cat’.",
    diet: "Fruit, berries and small animals, including insects.", activity: "Nocturnal; usually rests out of sight by day.",
    behaviour: "Often forages alone, using branches and the ground. Adaptability allows it to visit gardens and buildings beside green spaces.",
    reproduction: "Females give birth to dependent young in sheltered places. Avoid disturbing roof spaces or tree hollows occupied by a family.",
    singapore: "A native resident of wooded areas and some neighbourhoods. The name Sumatran palm civet follows NParks’ current species table.",
    ecologicalRole: "Passes seeds from eaten fruit, helping seed dispersal.",
    pressures: "Road crossings, loss of shelter and conflict around homes. Wildlife-friendly coexistence is preferable to feeding or trapping.",
    watch: "Secure food waste and allow it to leave. If young are present, seek AVS advice before closing an access hole.",
    funFacts: [{ title: "An after-dark gardener", text: "Seeds from fruit meals can be spread in a civet’s droppings." }, { title: "A misleading nickname", text: "A ‘toddy cat’ belongs to the civet family, not the cat family.", sourceUrl: "https://avs.nparks.gov.sg/wildlife/encountering-wildlife/civets/" }],
    sources: [avs("civets")], taxonomyNote: "NParks RDB3 lists Paradoxurus musangus. Older ‘common palm civet’ material may use a broader Paradoxurus hermaphroditus concept; its global assessment is not automatically transferred here.",
  },
  "Sus scrofa": {
    id: "wild-boar", group: "Mammal", family: "Suidae", aliases: ["Eurasian wild boar", "wild pig"], origin: "Native", encounter: "Commonly seen", habitats: ["Forest", "Scrub", "Parks"],
    summary: "One of Singapore’s largest land mammals. Its strong snout turns leaf litter and soil while it searches for food, so disturbed ground can be a clue to its presence.",
    identification: "A stocky body with coarse dark hair, an elongated snout and short legs. Young piglets have pale lengthwise stripes that fade with age.",
    diet: "Roots, fruit and other plant parts, plus invertebrates and carrion.", activity: "Can be active by day or night; timing changes with disturbance.",
    behaviour: "Roots through the ground for food. Females may travel with young; an animal with piglets or no escape route needs particular space.",
    reproduction: "Females give birth to litters and nurse their piglets. Young follow their mother after an early period in shelter.",
    singapore: "Occurs in forests and adjoining green areas, and may enter urban spaces. Encounter frequency varies greatly between places.",
    ecologicalRole: "An omnivore whose rooting changes soil and leaf litter.",
    pressures: "Human food, roads and encounters near urban edges can lead to conflict. Never encourage it to approach people.",
    watch: "Stay calm, keep your distance and avoid separating adults from piglets. Do not feed or corner a boar.",
    funFacts: [{ title: "Stripy beginnings", text: "Piglets have pale stripes that become less obvious as they grow." }, { title: "A nose for a meal", text: "Its snout is a useful digging tool for roots and hidden food." }],
    sources: [adw("Sus_scrofa"), avs("wild-boars")],
  },
  "Tragulus kanchil": {
    id: "lesser-mousedeer", group: "Mammal", family: "Tragulidae", aliases: ["lesser mouse-deer", "mouse deer", "Sang Kancil"], origin: "Native", encounter: "Rare or restricted", habitats: ["Forest"],
    summary: "A tiny hoofed forest mammal with a delicate build. It belongs to the chevrotain family, rather than being a mouse or a miniature member of the true deer family.",
    identification: "Very slender legs, an arched back, a small pointed face and pale throat markings. It has no antlers.",
    diet: "Fallen fruit, young leaves and other forest plant material.", activity: "Secretive; often concealed in dense undergrowth.",
    behaviour: "Moves cautiously through leaf litter. Males have elongated upper canine teeth rather than antlers.",
    reproduction: "Gives birth to live young, which are nursed by the mother. Breeding dates are not inferred from isolated local sightings.",
    singapore: "Largely associated with mature, dense forest in the Central Nature Reserves. Restricted habitat and quiet behaviour make it difficult to observe.",
    ecologicalRole: "A small terrestrial herbivore in the forest-floor food web.",
    pressures: "Loss and fragmentation of mature forest reduce suitable cover and feeding habitat.",
    watch: "Remain on trails and let it disappear into cover. Do not pursue it for a closer photograph.",
    funFacts: [{ title: "Fangs instead of antlers", text: "Males have extended canine teeth; neither sex grows antlers." }, { title: "A storybook animal", text: "The mousedeer, Sang Kancil, is a clever character in Malay folklore." }],
    sources: [],
  },
  "Cynopterus brachyotis": {
    id: "lesser-dog-faced-fruit-bat", group: "Mammal", family: "Pteropodidae", aliases: ["lesser short-nosed fruit bat", "common fruit bat", "fruit bat"], origin: "Native", encounter: "Elusive", habitats: ["Forest", "Parks", "Urban"],
    summary: "A small fruit bat that can live in gardens and other urban greenery. Bats are mammals with true powered flight; this species searches for plant food after dark.",
    identification: "Brown fur, large eyes, a dog-like muzzle and pale edges along the ears and wing bones. A fast silhouette alone is not enough for species identification.",
    diet: "Fruit and nectar.", activity: "Nocturnal.",
    behaviour: "Roosts in small groups in trees, beneath leaves and sometimes buildings. Fruit-bearing plants provide feeding stops across its range.",
    reproduction: "Usually bears one pup at a time. Like other mammals, the mother feeds her young with milk.",
    singapore: "NParks describes it as widespread and common, including in urban areas. Being hard to identify in flight is different from being nationally rare.",
    ecologicalRole: "Helps spread seeds from fruit and can visit flowers for nectar.",
    pressures: "Loss of roosts and fruiting vegetation can remove shelter and food.",
    watch: "Do not handle a bat or disturb a roost. Observe from a distance and seek professional help for an injured animal.",
    funFacts: [{ title: "Mammals with wings", text: "A fruit bat uses powered flight; the colugo moves by gliding instead." }, { title: "White-edged ears", text: "Pale edging on the ears and wing bones is a useful close-view feature in reference photos." }],
    sources: [adw("Cynopterus_brachyotis"), avs("bats")],
  },
  "Acridotheres javanicus": {
    id: "javan-myna", group: "Bird", family: "Sturnidae", aliases: ["white-vented myna", "myna"], origin: "Introduced", encounter: "Commonly seen", habitats: ["Urban", "Parks"],
    summary: "A very familiar urban bird in Singapore, introduced through human activity. Its success around people does not make it a native species.",
    identification: "Dark grey-black plumage, yellow bill and legs, pale yellow eyes and a short forehead crest. White wing patches show clearly in flight.",
    diet: "An adaptable omnivore eating insects, fruit and other available food.", activity: "Diurnal; gathers at evening roosts.",
    behaviour: "Forages on lawns, pavements and in trees. Many individuals can roost together in the same tree.",
    reproduction: "Nests in cavities, including suitable openings in buildings. Urban structures can provide many possible nest sites.",
    singapore: "Widespread and commonly seen near people. Its national assessment is Not Applicable because it is introduced.",
    ecologicalRole: "An urban omnivore that also competes for food and nesting cavities.",
    pressures: "Abundant food waste supports concentrations near homes. National non-native status is separate from its conservation position in its native range.",
    watch: "Dispose of food properly and do not feed. Leave active nests and roosting birds undisturbed.",
    funFacts: [{ title: "White flashes", text: "A dark myna reveals bold white wing patches when it takes flight." }, { title: "Communal bedtime", text: "Mynas gather in shared tree roosts, sometimes in large groups.", sourceUrl: "https://avs.nparks.gov.sg/wildlife/encountering-wildlife/house-crows-pigeons-javan-mynas/javan-mynas/" }],
    sources: [avs("house-crows-pigeons-javan-mynas/javan-mynas")],
  },
  "Corvus splendens": {
    id: "house-crow", group: "Bird", family: "Corvidae", aliases: ["crow"], origin: "Introduced", encounter: "Commonly seen", habitats: ["Urban", "Parks", "Mangrove"],
    summary: "An adaptable crow commonly seen around Singapore’s built areas. It originated in the Indian subcontinent and is an introduced resident here.",
    identification: "A black head and wings contrast with a greyer neck and breast. The grey collar is a better starting clue than simply calling any black bird a crow.",
    diet: "A wide range of food, including invertebrates, fruit, carrion and accessible food waste.", activity: "Diurnal.",
    behaviour: "Forages opportunistically and can gather around reliable food. Breeding adults may defend the area around their nest or young.",
    reproduction: "An egg-laying bird that builds a nest and raises chicks. Defensive swooping can be associated with breeding and does not mean the bird is hunting people.",
    singapore: "Common in urban environments and also uses coastal and mangrove settings. It is listed as introduced and nationally Not Applicable.",
    ecologicalRole: "A scavenger and omnivore, with possible effects on other birds’ eggs and young.",
    pressures: "Food waste and close nesting beside people can lead to conflict.",
    watch: "Avoid a defended nesting area and do not feed. Report persistent attacks through the current AVS guidance page.",
    funFacts: [{ title: "A grey collar", text: "The house crow is not entirely black: look for its greyer neck and chest." }, { title: "Protective parents", text: "Swooping at people may be a nest-defence response.", sourceUrl: "https://avs.nparks.gov.sg/wildlife/encountering-wildlife/house-crows-pigeons-javan-mynas/house-crows/" }],
    sources: [avs("house-crows-pigeons-javan-mynas/house-crows")],
  },
  "Eudynamys scolopaceus": {
    id: "asian-koel", group: "Bird", family: "Cuculidae", aliases: ["koel", "uwu bird", "Eudynamys scolopacea"], origin: "Native", encounter: "Commonly seen", habitats: ["Forest", "Parks", "Urban"],
    summary: "The loud morning caller many Singapore residents know by sound. It is a cuckoo whose chicks are raised in another bird’s nest.",
    identification: "Males are glossy black with a pale bill and red eyes. Females are brown with pale spots and bars, so the two sexes look quite different.",
    diet: "Mainly fruit, with other food taken opportunistically.", activity: "Diurnal; calling can begin early in the morning.",
    behaviour: "Often stays in foliage around fruiting trees. Its repeated call is more conspicuous than the bird itself.",
    reproduction: "Lays eggs in other birds’ nests, including crows’ nests. The host adults provide the chick’s care: this is called brood parasitism.",
    singapore: "Common in secondary woodland, gardens, parks and other urban greenery. It is a native resident, not an introduced noise-making species.",
    ecologicalRole: "A fruit consumer and brood parasite in the local bird community.",
    pressures: "Loss of fruiting trees removes food. Managing noise complaints should not involve disturbing wildlife nests.",
    watch: "Listen from a distance and avoid playback. Do not search for or interfere with a host nest.",
    funFacts: [{ title: "Foster parents", text: "A koel chick can be raised by a crow after its egg was laid in the crow’s nest." }, { title: "Two very different looks", text: "The spotted brown female looks quite different from the glossy black male." }],
    sources: [avs("other-birds/asian-koels")], taxonomyNote: "RDB3 uses Eudynamys scolopaceus; some NParks learning material spells the epithet scolopacea. Both names are included in search.",
  },
  "Oriolus chinensis": {
    id: "black-naped-oriole", group: "Bird", family: "Oriolidae", aliases: ["oriole", "kunyit besar"], origin: "Native", encounter: "Commonly seen", habitats: ["Parks", "Forest", "Urban"],
    summary: "A bright yellow bird of Singapore’s tree canopy. Its distinctive colour can stand out in flight but disappear surprisingly well among sunlit leaves.",
    identification: "Yellow body, black wings and a broad dark eye band continuing around the back of the head. Adults have a pinkish bill; young birds have streakier underparts.",
    diet: "Fruit and insects.", activity: "Diurnal.",
    behaviour: "Forages in trees and may join other birds at fruiting plants. Look high in the foliage and listen as well as watch.",
    reproduction: "Builds a cup-like nest suspended in a fork of branches. Eggs and young stay protected within the nest.",
    singapore: "Widespread in parks, gardens and other wooded settings. It is listed as native and nationally Least Concern.",
    ecologicalRole: "Consumes fruit and insects in the canopy food web.",
    pressures: "Retention of mature trees and food plants supports nesting and foraging.",
    watch: "Watch feeding birds from the path. Avoid pointing out or approaching active nests.",
    funFacts: [{ title: "Turmeric yellow", text: "Its Malay name, ‘kunyit besar’, refers to the bird’s striking yellow colour." }, { title: "A changing bill", text: "Young birds have a greyer bill than the pink-billed adults." }],
    sources: [{ name: "Bird Society of Singapore · oriole profile", url: "https://singaporebirds.com/species/black-naped-oriole", supports: "Identification, habitat and diet" }, np("https://juronglakegardens.nparks.gov.sg/birds/", "Garden-bird ecology and nesting")],
  },
  "Todiramphus chloris": {
    id: "collared-kingfisher", group: "Bird", family: "Alcedinidae", aliases: ["white-collared kingfisher", "mangrove kingfisher"], origin: "Native", encounter: "Commonly seen", habitats: ["Mangrove", "Coast", "Parks"],
    summary: "A familiar kingfisher that is not limited to fishing. It watches from a perch and can hunt small land animals well away from water.",
    identification: "Blue-green upperparts with a white collar and belly. The large bill is dark, unlike the red bill of a white-throated kingfisher.",
    diet: "Fish, small amphibians, lizards and insects.", activity: "Diurnal.",
    behaviour: "Hunts from fences, wires and exposed branches. Usually territorial outside the breeding period.",
    reproduction: "Nests in a cavity or burrow. Do not inspect an opening or approach birds repeatedly carrying food to it.",
    singapore: "Common along coasts and canals and in parks, including suitable mangrove habitats. NParks describes it as the most common local kingfisher.",
    ecologicalRole: "A small predator using both terrestrial and waterside food webs.",
    pressures: "Loss of vegetation, perches and nesting cover reduces useful habitat.",
    watch: "Use binoculars from a fixed point. Let the bird resume hunting rather than following it between perches.",
    funFacts: [{ title: "More than a fisher", text: "Its menu includes lizards and insects, so it can live away from water." }, { title: "A white collar", text: "The clear white neck marking gives this kingfisher its name." }],
    sources: [np("https://www.nparks.gov.sg/florafaunaweb/fauna/3/4/34"), { name: "Bird Society of Singapore · kingfisher profile", url: "https://singaporebirds.com/species/collared-kingfisher", supports: "Species identification and natural history" }],
  },
  "Gallus gallus": {
    id: "red-junglefowl", group: "Bird", family: "Phasianidae", aliases: ["junglefowl", "wild chicken"], origin: "Native", encounter: "Commonly seen", habitats: ["Forest", "Scrub", "Parks"],
    summary: "The wild relative of domestic chickens. Singapore also has free-ranging domestic and hybrid chickens, so every rooster in a park must not be labelled a pure red junglefowl.",
    identification: "Males have orange-red neck feathers, dark glossy tails and a red comb. Females are mottled brown. Domestic ancestry cannot be ruled out from one visible trait.",
    diet: "Seeds, roots and small invertebrates found on the ground.", activity: "Diurnal; roosts in trees at night.",
    behaviour: "Scratches and pecks through ground cover. Groups have social relationships, with males displaying and crowing.",
    reproduction: "Females lay eggs in a ground nest and care for chicks. The young can follow the mother and feed themselves soon after hatching.",
    singapore: "Native wild birds and admixed free-ranging birds occur locally. The national Near Threatened assessment applies to the wild species, not all domestic chickens.",
    ecologicalRole: "A ground-foraging omnivore that eats seeds and small animals.",
    pressures: "Hybridisation with domestic chickens, trapping and loss of suitable habitat.",
    watch: "Do not feed or chase. Give hens with chicks room to move and leave ground nests alone.",
    funFacts: [{ title: "Upstairs at night", text: "Despite feeding on the ground, junglefowl roost in trees." }, { title: "Look twice at that rooster", text: "Free-ranging chickens may have domestic ancestry, even when they resemble wild junglefowl." }],
    sources: [], statusNote: "The older Flora & Fauna Web account cites Endangered under RDB2. RDB3 lists the wild species as Near Threatened. Old population estimates are not presented as current counts.",
  },
  "Varanus salvator": {
    id: "malayan-water-monitor", group: "Reptile", family: "Varanidae", aliases: ["water monitor", "monitor lizard", "Asian water monitor"], origin: "Native", encounter: "Commonly seen", habitats: ["Mangrove", "Freshwater", "Parks"],
    summary: "A large lizard commonly seen beside Singapore’s water. It is an able swimmer, but can also walk on land and climb trees.",
    identification: "Long neck, forked tongue, sturdy claws and a powerful tail. Young animals show yellowish spots and bands that can fade as they mature.",
    diet: "Small animals, including fish, and carrion.", activity: "Diurnal.",
    behaviour: "Searches for food near water and may bask on banks. Its forked tongue samples chemical cues in the environment.",
    reproduction: "Females lay eggs in sheltered sites on land, including suitable decaying wood or soil. Young monitors are independent after hatching.",
    singapore: "Widespread, including mangroves, ponds and parks. A large water monitor is a lizard, not a juvenile crocodile.",
    ecologicalRole: "Both predator and scavenger in waterside food webs.",
    pressures: "Unsafe encounters, road crossings and disturbance can affect animals living beside people.",
    watch: "Give it space and a route away. Do not feed, touch or provoke it; a defensive bite can injure.",
    funFacts: [{ title: "Spots that fade", text: "Young water monitors have brighter spotted patterns than many large adults." }, { title: "Three ways to travel", text: "It can walk, climb and swim." }],
    sources: [adw("Varanus_salvator"), avs("monitor-lizards")],
  },
  "Malayopython reticulatus": {
    id: "reticulated-python", group: "Reptile", family: "Pythonidae", aliases: ["Python reticulatus", "python"], origin: "Native", encounter: "Elusive", habitats: ["Forest", "Freshwater", "Urban"],
    summary: "A large native snake with a network-like pattern. It is non-venomous but powerful, and should always be observed without handling or cornering it.",
    identification: "Tan or yellow-brown ground colour crossed by dark geometric lines and pale side patches. Its shape and pattern differ from a uniformly dark cobra.",
    diet: "Mammals, including rodents; larger individuals can take larger prey.", activity: "Often nocturnal or hidden during daylight.",
    behaviour: "Ambushes prey, constricts it and swallows it whole. It is mainly terrestrial but can climb well.",
    reproduction: "Lays eggs; the female coils around the clutch during incubation. Eggs and resting snakes must not be moved by visitors.",
    singapore: "A native resident using natural and urban habitats. A drain or green corridor can provide cover, so sightings are not limited to forests.",
    ecologicalRole: "A predator of rodents and other mammals.",
    pressures: "Road collisions, persecution and conflict in built environments.",
    watch: "Keep people and pets away and allow an escape route. Contact a wildlife professional if it is trapped or inside a building.",
    funFacts: [{ title: "A net of markings", text: "‘Reticulated’ describes the net-like pattern running along its body." }, { title: "No venom needed", text: "It subdues prey by constriction, rather than injecting venom.", sourceUrl: "https://biodiversitysg.nparks.gov.sg/our-ecosystems/food-webs/food-webs-in-our-forests/" }],
    sources: [adw("Python_reticulatus"), avs("snakes")],
  },
  "Naja sumatrana": {
    id: "equatorial-spitting-cobra", group: "Reptile", family: "Elapidae", aliases: ["black spitting cobra", "cobra"], origin: "Native", encounter: "Elusive", habitats: ["Forest", "Scrub", "Urban"],
    summary: "A venomous native snake that sometimes enters built areas. Learning about it should build respect and safe distance, never encourage approaching or handling.",
    identification: "Often glossy black locally, with a broad head and an expandable hood. A snake does not need to raise its hood to be dangerous.",
    diet: "Small animals, including rats and toads.", activity: "Often diurnal, though an encounter is possible at other times.",
    behaviour: "May raise the forebody, spread the hood and hiss when threatened. It can also spray venom defensively toward an attacker’s eyes.",
    reproduction: "An egg-laying snake. Do not disturb hidden snakes, egg sites or shelter; young snakes must also be left alone.",
    singapore: "NParks describes it as common in scrub and suburban habitats. Its secretive nature means encounter frequency and national threat status are different measures.",
    ecologicalRole: "A predator of small vertebrates in terrestrial food webs.",
    pressures: "Killing through fear and conflict with people can harm native snakes.",
    watch: "Back away and keep others and pets away. Never try to catch it; seek urgent medical help for a bite or venom exposure.",
    funFacts: [{ title: "A warning display", text: "A hood and hiss are defensive warnings, not an invitation to move closer." }, { title: "A useful hunter", text: "Rats and toads are among this cobra’s natural prey." }],
    sources: [avs("snakes")],
  },
  "Hemidactylus frenatus": {
    id: "common-house-gecko", group: "Reptile", family: "Gekkonidae", aliases: ["spiny-tailed house gecko", "house lizard", "gecko"], origin: "Native", encounter: "Commonly seen", habitats: ["Urban", "Parks", "Forest"],
    summary: "A small night-active lizard familiar on walls and near lights. Several gecko species use Singapore’s buildings, so a distant outline is not enough for a certain identification.",
    identification: "Expanded toe pads, thin skin and small spines around an original tail. A regrown tail can look different, so tail shape alone is not conclusive.",
    diet: "Insects and other small invertebrates.", activity: "Nocturnal; shelters in cracks by day.",
    behaviour: "Climbs walls and trees to hunt. It may shed its tail when threatened, giving it a chance to escape.",
    reproduction: "Females usually lay two small, hard-shelled eggs in protected places. Hatchlings are miniature lizards, without a tadpole stage.",
    singapore: "Common in buildings and nearby wooded areas. It is listed in Singapore’s national reptile assessment as Least Concern.",
    ecologicalRole: "A small insect predator around buildings and vegetation.",
    pressures: "Sticky traps and pesticides can harm geckos and their prey.",
    watch: "Do not catch it by the tail. Avoid glue traps and let it move away normally.",
    funFacts: [{ title: "A spare-tail escape", text: "A gecko can shed its tail to distract a threat, but the replacement is not identical." }, { title: "Tiny shelled eggs", text: "Its eggs have hard shells rather than the soft jelly around frog eggs.", sourceUrl: "https://animaldiversity.org/accounts/Hemidactylus_frenatus/" }],
    sources: [adw("Hemidactylus_frenatus")],
  },
  "Kaloula pulchra": {
    id: "banded-bullfrog", group: "Amphibian", family: "Microhylidae", aliases: ["Asian painted frog", "banded bull frog"], origin: "Introduced", encounter: "Commonly seen", habitats: ["Urban", "Parks", "Freshwater"],
    summary: "A round-bodied frog often heard after rain in Singapore. It adapts well to gardens and built areas but is recorded by NParks as introduced here.",
    identification: "A small head, rounded body and two broad pale bands against a darker back. It can inflate its body when threatened.",
    diet: "Ants, termites and other small invertebrates.", activity: "Mostly nocturnal; calling often follows rain.",
    behaviour: "Shelters in covered places and can climb as well as move on the ground. Its low call may carry farther than expected from its size.",
    reproduction: "Gathers near temporary pools or other still water to breed. Eggs develop into aquatic tadpoles before metamorphosis into frogs.",
    singapore: "Common in gardens, parks and other built environments. Being well established is different from being native.",
    ecologicalRole: "Consumes small invertebrates and is itself prey for other animals.",
    pressures: "Traffic and loss of usable breeding water affect encounters locally. Do not introduce frogs or tadpoles to new sites.",
    watch: "Listen after rain from a safe path. Leave adults, eggs and tadpoles in place.",
    funFacts: [{ title: "Puff-up defence", text: "A threatened bullfrog can inflate its body to appear larger." }, { title: "Rainy-night chorus", text: "Its calls are often heard around heavy rain, even when the frog stays hidden." }],
    sources: [np("https://www.nparks.gov.sg/florafaunaweb/fauna/4/5/455", "Introduced origin and common occurrence")], statusNote: "The linked NParks species profile records it as introduced. No RDB3 row is claimed here; the guide shows ‘Not assessed here’ instead of inventing a threat category.",
  },
  "Polypedates leucomystax": {
    id: "four-lined-tree-frog", group: "Amphibian", family: "Rhacophoridae", aliases: ["common tree frog", "tree frog"], origin: "Native", encounter: "Commonly seen", habitats: ["Forest", "Parks", "Urban", "Freshwater"],
    summary: "A climbing frog of trees, shrubs and gardens. It uses vegetation for hunting and puts its eggs in foam above water rather than laying an exposed mass in a pond.",
    identification: "Slender limbs, a pointed snout and expanded toe pads. Four dark back stripes are common, but some individuals are spotted or less clearly marked.",
    diet: "Insects and other small invertebrates.", activity: "Nocturnal.",
    behaviour: "Climbs vegetation with its toe pads. Calling can reveal animals that blend into leaves and bark.",
    reproduction: "Builds a foam nest over water. After hatching, tadpoles drop into the water and continue development there.",
    singapore: "A common native frog of suburban and rural greenery, as well as disturbed forest. It is nationally Least Concern in RDB3.",
    ecologicalRole: "An insect predator above ground, with an aquatic tadpole stage linking land and water.",
    pressures: "Loss of vegetation and breeding water, disturbance and chemical pollution can reduce suitable habitat.",
    watch: "Do not peel open foam nests, collect tadpoles or handle the frogs. Watch from the path.",
    funFacts: [{ title: "A foamy nursery", text: "Its eggs begin life inside foam above water; the tadpoles later drop into the water." }, { title: "Four lines… sometimes", text: "Not every four-lined tree frog has four clear stripes." }],
    sources: [np("https://www.nparks.gov.sg/florafaunaweb/fauna/4/4/446", "Identification, native origin and local occurrence")],
  },
};
